<?php

namespace App\Jobs\Knowledge;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

/**
 * Auto-generates comprehensive database schema map including:
 * - All schemas and tables
 * - Column definitions
 * - Foreign key relationships
 * - RLS policies
 * - Indexes and performance metrics
 *
 * Generated File: .claude/knowledge/auto-generated/DATABASE_SCHEMA_MAP.md
 */
class DiscoverDatabaseSchema implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected string $outputPath;

    public function __construct()
    {
        $this->outputPath = base_path('.claude/knowledge/auto-generated/DATABASE_SCHEMA_MAP.md');
    }

    public function handle(): void
    {
        $content = $this->generateSchemaMap();

        // Ensure directory exists
        File::ensureDirectoryExists(dirname($this->outputPath));

        // Write generated knowledge
        File::put($this->outputPath, $content);

        \Log::info('Database schema map generated', [
            'file' => $this->outputPath,
            'size' => File::size($this->outputPath),
        ]);
    }

    protected function generateSchemaMap(): string
    {
        $timestamp = now()->toIso8601String();

        $markdown = "# Auto-Generated Database Schema Map\n\n";
        $markdown .= "**Last Updated:** {$timestamp}\n";
        $markdown .= "**Generated By:** cmis-knowledge-maintainer agent\n\n";
        $markdown .= "---\n\n";

        // Schema Summary
        $markdown .= $this->discoverSchemas();

        // Tables by Schema
        $markdown .= $this->discoverTables();

        // Foreign Key Relationships
        $markdown .= $this->discoverForeignKeys();

        // RLS Policies
        $markdown .= $this->discoverRLSPolicies();

        // Indexes
        $markdown .= $this->discoverIndexes();

        // Discovery Commands
        $markdown .= $this->appendDiscoveryCommands();

        return $markdown;
    }

    protected function discoverSchemas(): string
    {
        $markdown = "## 📊 Schema Summary\n\n";

        // Get all CMIS schemas
        $schemas = DB::select("
            SELECT
                schemaname,
                COUNT(*) as table_count,
                pg_size_pretty(SUM(pg_total_relation_size(schemaname||'.'||tablename))) as total_size
            FROM pg_tables
            WHERE schemaname LIKE 'cmis%'
            GROUP BY schemaname
            ORDER BY schemaname
        ");

        $totalSchemas = count($schemas);
        $totalTables = array_sum(array_column($schemas, 'table_count'));

        $markdown .= "### Statistics\n\n";
        $markdown .= "- **Total Schemas:** {$totalSchemas}\n";
        $markdown .= "- **Total Tables:** {$totalTables}\n\n";

        $markdown .= "### Schema Details\n\n";
        $markdown .= "| Schema | Tables | Total Size |\n";
        $markdown .= "|--------|--------|------------|\n";

        foreach ($schemas as $schema) {
            $markdown .= "| `{$schema->schemaname}` | {$schema->table_count} | {$schema->total_size} |\n";
        }

        $markdown .= "\n---\n\n";

        return $markdown;
    }

    protected function discoverTables(): string
    {
        $markdown = "## 📋 Tables by Schema\n\n";

        // Get all tables with details
        $tables = DB::select("
            SELECT
                schemaname,
                tablename,
                pg_size_pretty(pg_total_relation_size(schemaname||'.'||tablename)) as size,
                (SELECT count(*)
                 FROM information_schema.columns
                 WHERE table_schema = schemaname AND table_name = tablename) as column_count,
                (SELECT rowsecurity FROM pg_tables pt
                 WHERE pt.schemaname = pg_tables.schemaname AND pt.tablename = pg_tables.tablename) as rls_enabled
            FROM pg_tables
            WHERE schemaname LIKE 'cmis%'
            ORDER BY schemaname, tablename
        ");

        $currentSchema = null;

        foreach ($tables as $table) {
            if ($currentSchema !== $table->schemaname) {
                if ($currentSchema !== null) {
                    $markdown .= "\n";
                }
                $markdown .= "### Schema: `{$table->schemaname}`\n\n";
                $currentSchema = $table->schemaname;
            }

            $rlsStatus = $table->rls_enabled ? '✅ Enabled' : '❌ Disabled';

            $markdown .= "#### Table: `{$table->tablename}`\n\n";
            $markdown .= "- **Size:** {$table->size}\n";
            $markdown .= "- **Columns:** {$table->column_count}\n";
            $markdown .= "- **RLS:** {$rlsStatus}\n";

            // Get column details
            $columns = $this->getTableColumns($table->schemaname, $table->tablename);
            if (!empty($columns)) {
                $markdown .= "- **Columns:**\n";
                $markdown .= "  | Column | Type | Nullable | Default |\n";
                $markdown .= "  |--------|------|----------|----------|\n";
                foreach ($columns as $column) {
                    $nullable = $column->is_nullable === 'YES' ? 'YES' : 'NO';
                    $default = $column->column_default ?? '-';
                    if (strlen($default) > 30) {
                        $default = substr($default, 0, 27) . '...';
                    }
                    $markdown .= "  | `{$column->column_name}` | {$column->data_type} | {$nullable} | {$default} |\n";
                }
            }

            $markdown .= "\n";
        }

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function getTableColumns(string $schema, string $table): array
    {
        return DB::select("
            SELECT
                column_name,
                data_type,
                is_nullable,
                column_default
            FROM information_schema.columns
            WHERE table_schema = ?
                AND table_name = ?
            ORDER BY ordinal_position
        ", [$schema, $table]);
    }

    protected function discoverForeignKeys(): string
    {
        $markdown = "## 🔗 Foreign Key Relationships\n\n";

        $foreignKeys = DB::select("
            SELECT
                tc.table_schema,
                tc.table_name,
                kcu.column_name,
                ccu.table_schema AS foreign_table_schema,
                ccu.table_name AS foreign_table_name,
                ccu.column_name AS foreign_column_name,
                rc.delete_rule,
                rc.update_rule
            FROM information_schema.table_constraints AS tc
            JOIN information_schema.key_column_usage AS kcu
                ON tc.constraint_name = kcu.constraint_name
                AND tc.table_schema = kcu.table_schema
            JOIN information_schema.constraint_column_usage AS ccu
                ON ccu.constraint_name = tc.constraint_name
                AND ccu.table_schema = tc.table_schema
            JOIN information_schema.referential_constraints AS rc
                ON tc.constraint_name = rc.constraint_name
                AND tc.table_schema = rc.constraint_schema
            WHERE tc.constraint_type = 'FOREIGN KEY'
                AND tc.table_schema LIKE 'cmis%'
            ORDER BY tc.table_schema, tc.table_name, kcu.column_name
        ");

        if (empty($foreignKeys)) {
            $markdown .= "*No foreign keys found.*\n\n";
        } else {
            $markdown .= "### Relationship Map\n\n";

            $currentSchema = null;
            foreach ($foreignKeys as $fk) {
                if ($currentSchema !== $fk->table_schema) {
                    if ($currentSchema !== null) {
                        $markdown .= "\n";
                    }
                    $markdown .= "#### Schema: `{$fk->table_schema}`\n\n";
                    $currentSchema = $fk->table_schema;
                }

                $markdown .= "- `{$fk->table_name}.{$fk->column_name}` → `{$fk->foreign_table_schema}.{$fk->foreign_table_name}.{$fk->foreign_column_name}`\n";
                $markdown .= "  - **ON DELETE:** {$fk->delete_rule}\n";
                $markdown .= "  - **ON UPDATE:** {$fk->update_rule}\n\n";
            }
        }

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function discoverRLSPolicies(): string
    {
        $markdown = "## 🔒 Row-Level Security (RLS) Policies\n\n";

        // Get RLS status for all tables
        $rlsTables = DB::select("
            SELECT
                schemaname,
                tablename,
                rowsecurity
            FROM pg_tables
            WHERE schemaname LIKE 'cmis%'
            ORDER BY schemaname, tablename
        ");

        $enabledCount = 0;
        $disabledCount = 0;

        foreach ($rlsTables as $table) {
            if ($table->rowsecurity) {
                $enabledCount++;
            } else {
                $disabledCount++;
            }
        }

        $markdown .= "### RLS Status Summary\n\n";
        $markdown .= "- **RLS Enabled:** {$enabledCount} tables\n";
        $markdown .= "- **RLS Disabled:** {$disabledCount} tables\n\n";

        // Get detailed policies
        $policies = DB::select("
            SELECT
                schemaname,
                tablename,
                policyname,
                cmd,
                qual,
                with_check
            FROM pg_policies
            WHERE schemaname LIKE 'cmis%'
            ORDER BY schemaname, tablename, cmd
        ");

        if (!empty($policies)) {
            $markdown .= "### Policy Details\n\n";

            $currentTable = null;
            foreach ($policies as $policy) {
                $tableKey = "{$policy->schemaname}.{$policy->tablename}";

                if ($currentTable !== $tableKey) {
                    if ($currentTable !== null) {
                        $markdown .= "\n";
                    }
                    $markdown .= "#### Table: `{$policy->schemaname}.{$policy->tablename}`\n\n";
                    $currentTable = $tableKey;
                }

                $markdown .= "- **Policy:** `{$policy->policyname}`\n";
                $markdown .= "  - **Command:** {$policy->cmd}\n";
                $markdown .= "  - **USING:** `{$policy->qual}`\n";
                if ($policy->with_check) {
                    $markdown .= "  - **WITH CHECK:** `{$policy->with_check}`\n";
                }
                $markdown .= "\n";
            }
        }

        // Tables without RLS
        $noRlsTables = array_filter($rlsTables, fn($t) => !$t->rowsecurity);
        if (!empty($noRlsTables)) {
            $markdown .= "### ⚠️ Tables Without RLS\n\n";
            $markdown .= "*These tables do not have Row-Level Security enabled:*\n\n";

            foreach ($noRlsTables as $table) {
                $markdown .= "- `{$table->schemaname}.{$table->tablename}`\n";
            }
            $markdown .= "\n";
        }

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function discoverIndexes(): string
    {
        $markdown = "## 📑 Indexes\n\n";

        $indexes = DB::select("
            SELECT
                schemaname,
                tablename,
                indexname,
                indexdef
            FROM pg_indexes
            WHERE schemaname LIKE 'cmis%'
            ORDER BY schemaname, tablename, indexname
        ");

        if (empty($indexes)) {
            $markdown .= "*No indexes found.*\n\n";
        } else {
            $markdown .= "### Index Summary\n\n";
            $markdown .= "- **Total Indexes:** " . count($indexes) . "\n\n";

            $markdown .= "### Index Details\n\n";

            $currentTable = null;
            foreach ($indexes as $index) {
                $tableKey = "{$index->schemaname}.{$index->tablename}";

                if ($currentTable !== $tableKey) {
                    if ($currentTable !== null) {
                        $markdown .= "\n";
                    }
                    $markdown .= "#### Table: `{$index->schemaname}.{$index->tablename}`\n\n";
                    $currentTable = $tableKey;
                }

                $markdown .= "- **Index:** `{$index->indexname}`\n";
                $markdown .= "  ```sql\n";
                $markdown .= "  {$index->indexdef}\n";
                $markdown .= "  ```\n\n";
            }
        }

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function appendDiscoveryCommands(): string
    {
        $markdown = "## 🔍 Discovery Commands\n\n";
        $markdown .= "*Use these commands to discover current database state:*\n\n";

        $markdown .= "### Count All Tables\n\n";
        $markdown .= "```sql\n";
        $markdown .= "SELECT COUNT(*) as total_tables\n";
        $markdown .= "FROM information_schema.tables\n";
        $markdown .= "WHERE table_schema LIKE 'cmis%';\n";
        $markdown .= "```\n\n";

        $markdown .= "### List All Schemas\n\n";
        $markdown .= "```sql\n";
        $markdown .= "SELECT schemaname, COUNT(*) as table_count\n";
        $markdown .= "FROM pg_tables\n";
        $markdown .= "WHERE schemaname LIKE 'cmis%'\n";
        $markdown .= "GROUP BY schemaname\n";
        $markdown .= "ORDER BY schemaname;\n";
        $markdown .= "```\n\n";

        $markdown .= "### Check RLS Status\n\n";
        $markdown .= "```sql\n";
        $markdown .= "SELECT\n";
        $markdown .= "    schemaname,\n";
        $markdown .= "    tablename,\n";
        $markdown .= "    rowsecurity as rls_enabled\n";
        $markdown .= "FROM pg_tables\n";
        $markdown .= "WHERE schemaname LIKE 'cmis%'\n";
        $markdown .= "ORDER BY schemaname, tablename;\n";
        $markdown .= "```\n\n";

        $markdown .= "### List All Foreign Keys\n\n";
        $markdown .= "```sql\n";
        $markdown .= "SELECT\n";
        $markdown .= "    tc.table_schema || '.' || tc.table_name as from_table,\n";
        $markdown .= "    kcu.column_name as from_column,\n";
        $markdown .= "    ccu.table_schema || '.' || ccu.table_name as to_table,\n";
        $markdown .= "    ccu.column_name as to_column\n";
        $markdown .= "FROM information_schema.table_constraints AS tc\n";
        $markdown .= "JOIN information_schema.key_column_usage AS kcu\n";
        $markdown .= "    ON tc.constraint_name = kcu.constraint_name\n";
        $markdown .= "JOIN information_schema.constraint_column_usage AS ccu\n";
        $markdown .= "    ON ccu.constraint_name = tc.constraint_name\n";
        $markdown .= "WHERE tc.constraint_type = 'FOREIGN KEY'\n";
        $markdown .= "    AND tc.table_schema LIKE 'cmis%'\n";
        $markdown .= "ORDER BY tc.table_schema, tc.table_name;\n";
        $markdown .= "```\n\n";

        $markdown .= "### Get Table Size\n\n";
        $markdown .= "```sql\n";
        $markdown .= "SELECT\n";
        $markdown .= "    schemaname,\n";
        $markdown .= "    tablename,\n";
        $markdown .= "    pg_size_pretty(pg_total_relation_size(schemaname||'.'||tablename)) as size\n";
        $markdown .= "FROM pg_tables\n";
        $markdown .= "WHERE schemaname LIKE 'cmis%'\n";
        $markdown .= "ORDER BY pg_total_relation_size(schemaname||'.'||tablename) DESC;\n";
        $markdown .= "```\n\n";

        return $markdown;
    }
}
