<?php

namespace App\Jobs\Knowledge;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

/**
 * Auto-generates comprehensive codebase map including:
 * - All models and their relationships
 * - Controllers and service dependencies
 * - Repository patterns
 * - Trait usage (BaseModel, HasOrganization, ApiResponse)
 *
 * Generated File: .claude/knowledge/auto-generated/CODEBASE_MAP.md
 */
class DiscoverCodebaseMap implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected string $outputPath;

    public function __construct()
    {
        $this->outputPath = base_path('.claude/knowledge/auto-generated/CODEBASE_MAP.md');
    }

    public function handle(): void
    {
        $content = $this->generateCodebaseMap();

        // Ensure directory exists
        File::ensureDirectoryExists(dirname($this->outputPath));

        // Write generated knowledge
        File::put($this->outputPath, $content);

        \Log::info('Codebase map generated', [
            'file' => $this->outputPath,
            'size' => File::size($this->outputPath),
        ]);
    }

    protected function generateCodebaseMap(): string
    {
        $timestamp = now()->toIso8601String();

        $markdown = "# Auto-Generated Codebase Map\n\n";
        $markdown .= "**Last Updated:** {$timestamp}\n";
        $markdown .= "**Generated By:** cmis-knowledge-maintainer agent\n\n";
        $markdown .= "---\n\n";

        // Models Section
        $markdown .= $this->discoverModels();

        // Controllers Section
        $markdown .= $this->discoverControllers();

        // Services Section
        $markdown .= $this->discoverServices();

        // Repositories Section
        $markdown .= $this->discoverRepositories();

        // Middleware Section
        $markdown .= $this->discoverMiddleware();

        // Traits Section
        $markdown .= $this->discoverTraits();

        return $markdown;
    }

    protected function discoverModels(): string
    {
        $markdown = "## 📦 Models Discovery\n\n";

        $modelFiles = File::allFiles(app_path('Models'));
        $totalModels = count($modelFiles);

        // Count models using BaseModel
        $baseModelCount = 0;
        $hasOrganizationCount = 0;
        $modelsByNamespace = [];

        foreach ($modelFiles as $file) {
            $content = File::get($file->getPathname());
            $namespace = $this->extractNamespace($content);
            $className = $file->getFilenameWithoutExtension();

            if (!isset($modelsByNamespace[$namespace])) {
                $modelsByNamespace[$namespace] = [];
            }

            $modelInfo = [
                'name' => $className,
                'file' => str_replace(base_path() . '/', '', $file->getPathname()),
                'extends_base_model' => str_contains($content, 'extends BaseModel'),
                'uses_has_organization' => str_contains($content, 'use HasOrganization'),
                'relationships' => $this->extractRelationships($content),
                'table' => $this->extractTableName($content, $className),
                'traits' => $this->extractTraits($content),
            ];

            if ($modelInfo['extends_base_model']) {
                $baseModelCount++;
            }

            if ($modelInfo['uses_has_organization']) {
                $hasOrganizationCount++;
            }

            $modelsByNamespace[$namespace][] = $modelInfo;
        }

        // Summary stats
        $markdown .= "### Summary Statistics\n\n";
        $markdown .= "- **Total Models:** {$totalModels}\n";
        $markdown .= "- **Extends BaseModel:** {$baseModelCount} (" . round(($baseModelCount / $totalModels) * 100, 1) . "%)\n";
        $markdown .= "- **Uses HasOrganization:** {$hasOrganizationCount} (" . round(($hasOrganizationCount / $totalModels) * 100, 1) . "%)\n";
        $markdown .= "- **Namespaces:** " . count($modelsByNamespace) . "\n\n";

        // Detailed breakdown by namespace
        $markdown .= "### Models by Namespace\n\n";

        foreach ($modelsByNamespace as $namespace => $models) {
            $markdown .= "#### {$namespace}\n\n";
            $markdown .= "**Count:** " . count($models) . " models\n\n";

            foreach ($models as $model) {
                $markdown .= "##### {$model['name']}\n\n";
                $markdown .= "- **File:** `{$model['file']}`\n";
                $markdown .= "- **Table:** `{$model['table']}`\n";
                $markdown .= "- **Extends BaseModel:** " . ($model['extends_base_model'] ? '✅ Yes' : '❌ No') . "\n";
                $markdown .= "- **Uses HasOrganization:** " . ($model['uses_has_organization'] ? '✅ Yes' : '❌ No') . "\n";

                if (!empty($model['traits'])) {
                    $markdown .= "- **Traits:** " . implode(', ', $model['traits']) . "\n";
                }

                if (!empty($model['relationships'])) {
                    $markdown .= "- **Relationships:**\n";
                    foreach ($model['relationships'] as $relationship) {
                        $markdown .= "  - `{$relationship['type']}`: {$relationship['name']} → {$relationship['related']}\n";
                    }
                }

                $markdown .= "\n";
            }
        }

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function discoverControllers(): string
    {
        $markdown = "## 🎮 Controllers Discovery\n\n";

        $controllerFiles = File::allFiles(app_path('Http/Controllers'));
        $totalControllers = count($controllerFiles);
        $apiResponseCount = 0;

        $markdown .= "### Summary Statistics\n\n";

        $controllers = [];
        foreach ($controllerFiles as $file) {
            $content = File::get($file->getPathname());
            $className = $file->getFilenameWithoutExtension();

            $usesApiResponse = str_contains($content, 'use ApiResponse');
            if ($usesApiResponse) {
                $apiResponseCount++;
            }

            $controllers[] = [
                'name' => $className,
                'file' => str_replace(base_path() . '/', '', $file->getPathname()),
                'uses_api_response' => $usesApiResponse,
                'dependencies' => $this->extractConstructorDependencies($content),
                'methods' => $this->extractPublicMethods($content),
            ];
        }

        $markdown .= "- **Total Controllers:** {$totalControllers}\n";
        $markdown .= "- **Uses ApiResponse Trait:** {$apiResponseCount} (" . round(($apiResponseCount / $totalControllers) * 100, 1) . "%)\n\n";

        $markdown .= "### Controller Details\n\n";

        foreach ($controllers as $controller) {
            $markdown .= "#### {$controller['name']}\n\n";
            $markdown .= "- **File:** `{$controller['file']}`\n";
            $markdown .= "- **Uses ApiResponse:** " . ($controller['uses_api_response'] ? '✅ Yes' : '❌ No') . "\n";

            if (!empty($controller['dependencies'])) {
                $markdown .= "- **Injected Dependencies:**\n";
                foreach ($controller['dependencies'] as $dep) {
                    $markdown .= "  - `{$dep}`\n";
                }
            }

            if (!empty($controller['methods'])) {
                $markdown .= "- **Public Methods:** " . implode(', ', $controller['methods']) . "\n";
            }

            $markdown .= "\n";
        }

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function discoverServices(): string
    {
        $markdown = "## ⚙️ Services Discovery\n\n";

        $serviceFiles = File::allFiles(app_path('Services'));
        $totalServices = count($serviceFiles);

        $markdown .= "### Summary Statistics\n\n";
        $markdown .= "- **Total Services:** {$totalServices}\n\n";

        $markdown .= "### Service Details\n\n";

        $services = [];
        foreach ($serviceFiles as $file) {
            $content = File::get($file->getPathname());
            $className = $file->getFilenameWithoutExtension();

            $services[] = [
                'name' => $className,
                'file' => str_replace(base_path() . '/', '', $file->getPathname()),
                'dependencies' => $this->extractConstructorDependencies($content),
                'repository_usage' => $this->extractRepositoryUsage($content),
            ];
        }

        foreach ($services as $service) {
            $markdown .= "#### {$service['name']}\n\n";
            $markdown .= "- **File:** `{$service['file']}`\n";

            if (!empty($service['dependencies'])) {
                $markdown .= "- **Dependencies:**\n";
                foreach ($service['dependencies'] as $dep) {
                    $markdown .= "  - `{$dep}`\n";
                }
            }

            if (!empty($service['repository_usage'])) {
                $markdown .= "- **Uses Repositories:**\n";
                foreach ($service['repository_usage'] as $repo) {
                    $markdown .= "  - `{$repo}`\n";
                }
            }

            $markdown .= "\n";
        }

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function discoverRepositories(): string
    {
        $markdown = "## 🗄️ Repositories Discovery\n\n";

        $repositoryFiles = File::allFiles(app_path('Repositories'));
        $totalRepositories = count($repositoryFiles);

        $markdown .= "### Summary Statistics\n\n";
        $markdown .= "- **Total Repositories:** {$totalRepositories}\n\n";

        $markdown .= "### Repository Details\n\n";

        foreach ($repositoryFiles as $file) {
            $content = File::get($file->getPathname());
            $className = $file->getFilenameWithoutExtension();

            $markdown .= "#### {$className}\n\n";
            $markdown .= "- **File:** `" . str_replace(base_path() . '/', '', $file->getPathname()) . "`\n";

            // Extract model usage
            $models = $this->extractModelUsage($content);
            if (!empty($models)) {
                $markdown .= "- **Models Used:**\n";
                foreach ($models as $model) {
                    $markdown .= "  - `{$model}`\n";
                }
            }

            $markdown .= "\n";
        }

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function discoverMiddleware(): string
    {
        $markdown = "## 🛡️ Middleware Discovery\n\n";

        $middlewareFiles = File::allFiles(app_path('Http/Middleware'));
        $totalMiddleware = count($middlewareFiles);

        $markdown .= "### Summary Statistics\n\n";
        $markdown .= "- **Total Middleware:** {$totalMiddleware}\n\n";

        $markdown .= "### Middleware Details\n\n";

        foreach ($middlewareFiles as $file) {
            $className = $file->getFilenameWithoutExtension();

            $markdown .= "- **{$className}**\n";
            $markdown .= "  - File: `" . str_replace(base_path() . '/', '', $file->getPathname()) . "`\n\n";
        }

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function discoverTraits(): string
    {
        $markdown = "## 🔧 Traits Discovery\n\n";

        // Find all trait files
        $traitFiles = [];
        $paths = [
            app_path('Models/Concerns'),
            app_path('Http/Controllers/Concerns'),
            app_path('Traits'),
        ];

        foreach ($paths as $path) {
            if (File::isDirectory($path)) {
                $files = File::allFiles($path);
                foreach ($files as $file) {
                    $traitFiles[] = $file;
                }
            }
        }

        $markdown .= "### Summary Statistics\n\n";
        $markdown .= "- **Total Traits:** " . count($traitFiles) . "\n\n";

        $markdown .= "### Trait Details\n\n";

        foreach ($traitFiles as $file) {
            $className = $file->getFilenameWithoutExtension();

            $markdown .= "#### {$className}\n\n";
            $markdown .= "- **File:** `" . str_replace(base_path() . '/', '', $file->getPathname()) . "`\n\n";
        }

        $markdown .= "---\n\n";

        return $markdown;
    }

    // Helper methods

    protected function extractNamespace(string $content): string
    {
        preg_match('/namespace\s+([^;]+);/', $content, $matches);
        return $matches[1] ?? 'Unknown';
    }

    protected function extractTableName(string $content, string $className): string
    {
        // Check for explicit table name
        if (preg_match('/protected\s+\$table\s*=\s*[\'"]([^\'"]+)[\'"]/', $content, $matches)) {
            return $matches[1];
        }

        // Otherwise use Laravel convention
        return Str::snake(Str::pluralStudly($className));
    }

    protected function extractRelationships(string $content): array
    {
        $relationships = [];
        $relationshipTypes = ['belongsTo', 'hasMany', 'hasOne', 'belongsToMany', 'morphTo', 'morphMany'];

        foreach ($relationshipTypes as $type) {
            if (preg_match_all('/function\s+(\w+)\s*\([^)]*\)\s*[^{]*{\s*return\s+\$this->' . $type . '\s*\(([^)]+)\)/', $content, $matches, PREG_SET_ORDER)) {
                foreach ($matches as $match) {
                    $relationships[] = [
                        'type' => $type,
                        'name' => $match[1],
                        'related' => trim(explode(',', $match[2])[0], '\'" '),
                    ];
                }
            }
        }

        return $relationships;
    }

    protected function extractTraits(string $content): array
    {
        $traits = [];

        if (preg_match_all('/use\s+([^;]+);/', $content, $matches)) {
            foreach ($matches[1] as $trait) {
                $trait = trim($trait);
                // Skip namespace imports
                if (!str_contains($trait, '\\')) {
                    $traits[] = $trait;
                }
            }
        }

        return array_unique($traits);
    }

    protected function extractConstructorDependencies(string $content): array
    {
        $dependencies = [];

        if (preg_match('/__construct\s*\(([^)]*)\)/', $content, $matches)) {
            $params = explode(',', $matches[1]);
            foreach ($params as $param) {
                if (preg_match('/(?:protected|public|private)?\s*([A-Z][a-zA-Z0-9_\\\\]*)\s+\$/', trim($param), $typeMatch)) {
                    $dependencies[] = $typeMatch[1];
                }
            }
        }

        return $dependencies;
    }

    protected function extractPublicMethods(string $content): array
    {
        $methods = [];

        if (preg_match_all('/public\s+function\s+([a-zA-Z0-9_]+)\s*\(/', $content, $matches)) {
            $methods = $matches[1];
            // Remove constructor
            $methods = array_filter($methods, fn($m) => $m !== '__construct');
        }

        return array_values($methods);
    }

    protected function extractRepositoryUsage(string $content): array
    {
        $repositories = [];

        if (preg_match_all('/([A-Z][a-zA-Z0-9_]*Repository)/', $content, $matches)) {
            $repositories = array_unique($matches[1]);
        }

        return array_values($repositories);
    }

    protected function extractModelUsage(string $content): array
    {
        $models = [];

        // Look for use statements
        if (preg_match_all('/use\s+App\\\\Models\\\\([^;]+);/', $content, $matches)) {
            foreach ($matches[1] as $model) {
                $models[] = str_replace('\\', '\\\\', $model);
            }
        }

        return array_unique($models);
    }
}
