<?php

namespace App\Jobs\Knowledge;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\File;

/**
 * Auto-generates service layer connection map showing:
 * - Controller → Service → Repository → Model flows
 * - Service dependencies and injection patterns
 * - Platform integration flows
 * - Business logic layers
 *
 * Generated File: .claude/knowledge/auto-generated/SERVICE_LAYER_MAP.md
 */
class DiscoverServiceConnections implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected string $outputPath;
    protected array $controllers = [];
    protected array $services = [];
    protected array $repositories = [];

    public function __construct()
    {
        $this->outputPath = base_path('.claude/knowledge/auto-generated/SERVICE_LAYER_MAP.md');
    }

    public function handle(): void
    {
        $this->discoverControllers();
        $this->discoverServices();
        $this->discoverRepositories();

        $content = $this->generateServiceMap();

        // Ensure directory exists
        File::ensureDirectoryExists(dirname($this->outputPath));

        // Write generated knowledge
        File::put($this->outputPath, $content);

        \Log::info('Service layer map generated', [
            'file' => $this->outputPath,
            'size' => File::size($this->outputPath),
        ]);
    }

    protected function discoverControllers(): void
    {
        $controllerFiles = File::allFiles(app_path('Http/Controllers'));

        foreach ($controllerFiles as $file) {
            $content = File::get($file->getPathname());
            $className = $file->getFilenameWithoutExtension();

            $this->controllers[$className] = [
                'name' => $className,
                'file' => str_replace(base_path() . '/', '', $file->getPathname()),
                'dependencies' => $this->extractDependencies($content),
                'uses_api_response' => str_contains($content, 'use ApiResponse'),
                'routes' => $this->inferRoutes($className),
            ];
        }
    }

    protected function discoverServices(): void
    {
        $servicePaths = [
            app_path('Services'),
            app_path('Services/Platform'),
        ];

        foreach ($servicePaths as $path) {
            if (!File::isDirectory($path)) {
                continue;
            }

            $serviceFiles = File::allFiles($path);

            foreach ($serviceFiles as $file) {
                $content = File::get($file->getPathname());
                $className = $file->getFilenameWithoutExtension();

                $this->services[$className] = [
                    'name' => $className,
                    'file' => str_replace(base_path() . '/', '', $file->getPathname()),
                    'dependencies' => $this->extractDependencies($content),
                    'repository_usage' => $this->extractRepositoryUsage($content),
                    'model_usage' => $this->extractModelUsage($content),
                    'external_api_calls' => $this->extractExternalAPICalls($content),
                ];
            }
        }
    }

    protected function discoverRepositories(): void
    {
        if (!File::isDirectory(app_path('Repositories'))) {
            return;
        }

        $repositoryFiles = File::allFiles(app_path('Repositories'));

        foreach ($repositoryFiles as $file) {
            $content = File::get($file->getPathname());
            $className = $file->getFilenameWithoutExtension();

            $this->repositories[$className] = [
                'name' => $className,
                'file' => str_replace(base_path() . '/', '', $file->getPathname()),
                'model_usage' => $this->extractModelUsage($content),
            ];
        }
    }

    protected function generateServiceMap(): string
    {
        $timestamp = now()->toIso8601String();

        $markdown = "# Auto-Generated Service Layer Map\n\n";
        $markdown .= "**Last Updated:** {$timestamp}\n";
        $markdown .= "**Generated By:** cmis-knowledge-maintainer agent\n\n";
        $markdown .= "---\n\n";

        // Summary
        $markdown .= $this->generateSummary();

        // Flow diagrams
        $markdown .= $this->generateFlowDiagrams();

        // Controller details
        $markdown .= $this->generateControllerSection();

        // Service details
        $markdown .= $this->generateServiceSection();

        // Repository details
        $markdown .= $this->generateRepositorySection();

        // Platform integration flows
        $markdown .= $this->generatePlatformIntegrationSection();

        // Discovery commands
        $markdown .= $this->appendDiscoveryCommands();

        return $markdown;
    }

    protected function generateSummary(): string
    {
        $markdown = "## 📊 Service Layer Summary\n\n";

        $markdown .= "- **Controllers:** " . count($this->controllers) . "\n";
        $markdown .= "- **Services:** " . count($this->services) . "\n";
        $markdown .= "- **Repositories:** " . count($this->repositories) . "\n\n";

        // ApiResponse adoption
        $apiResponseCount = count(array_filter($this->controllers, fn($c) => $c['uses_api_response']));
        $percentage = count($this->controllers) > 0
            ? round(($apiResponseCount / count($this->controllers)) * 100, 1)
            : 0;

        $markdown .= "- **Controllers Using ApiResponse:** {$apiResponseCount}/{" . count($this->controllers) . "} ({$percentage}%)\n\n";

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function generateFlowDiagrams(): string
    {
        $markdown = "## 🔄 Common Data Flow Patterns\n\n";

        $markdown .= "### Pattern 1: Standard CRUD Flow\n\n";
        $markdown .= "```\n";
        $markdown .= "HTTP Request\n";
        $markdown .= "    ↓\n";
        $markdown .= "Controller (validates, delegates)\n";
        $markdown .= "    ↓ injects\n";
        $markdown .= "Service (business logic)\n";
        $markdown .= "    ↓ uses\n";
        $markdown .= "Repository (data access)\n";
        $markdown .= "    ↓ queries\n";
        $markdown .= "Model (Eloquent ORM)\n";
        $markdown .= "    ↓ interacts with (via RLS)\n";
        $markdown .= "Database Table\n";
        $markdown .= "```\n\n";

        $markdown .= "### Pattern 2: Platform Integration Flow\n\n";
        $markdown .= "```\n";
        $markdown .= "Controller\n";
        $markdown .= "    ↓ injects\n";
        $markdown .= "Platform Service\n";
        $markdown .= "    ↓ uses\n";
        $markdown .= "Platform Connector (Meta/Google/TikTok)\n";
        $markdown .= "    ↓ calls\n";
        $markdown .= "External Platform API\n";
        $markdown .= "    ↓ stores result via\n";
        $markdown .= "Repository → Model → Database\n";
        $markdown .= "```\n\n";

        $markdown .= "### Pattern 3: AI/Embedding Flow\n\n";
        $markdown .= "```\n";
        $markdown .= "Service (Campaign, Content, etc.)\n";
        $markdown .= "    ↓ dispatches\n";
        $markdown .= "EmbeddingOrchestrator\n";
        $markdown .= "    ↓ calls\n";
        $markdown .= "Google Gemini API\n";
        $markdown .= "    ↓ stores vector in\n";
        $markdown .= "pgvector (cmis_ai.embeddings)\n";
        $markdown .= "```\n\n";

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function generateControllerSection(): string
    {
        $markdown = "## 🎮 Controllers\n\n";

        foreach ($this->controllers as $controller) {
            $markdown .= "### {$controller['name']}\n\n";
            $markdown .= "- **File:** `{$controller['file']}`\n";
            $markdown .= "- **Uses ApiResponse:** " . ($controller['uses_api_response'] ? '✅ Yes' : '❌ No') . "\n";

            if (!empty($controller['routes'])) {
                $markdown .= "- **Likely Routes:** `{$controller['routes']}`\n";
            }

            if (!empty($controller['dependencies'])) {
                $markdown .= "- **Injected Dependencies:**\n";
                foreach ($controller['dependencies'] as $dep) {
                    $markdown .= "  - `{$dep}`\n";

                    // Try to link to service
                    $serviceName = $this->extractClassName($dep);
                    if (isset($this->services[$serviceName])) {
                        $markdown .= "    - ↓ Uses `{$serviceName}` service\n";
                    }
                }
            }

            $markdown .= "\n";
        }

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function generateServiceSection(): string
    {
        $markdown = "## ⚙️ Services\n\n";

        foreach ($this->services as $service) {
            $markdown .= "### {$service['name']}\n\n";
            $markdown .= "- **File:** `{$service['file']}`\n";

            if (!empty($service['dependencies'])) {
                $markdown .= "- **Dependencies:**\n";
                foreach ($service['dependencies'] as $dep) {
                    $markdown .= "  - `{$dep}`\n";
                }
            }

            if (!empty($service['repository_usage'])) {
                $markdown .= "- **Uses Repositories:**\n";
                foreach ($service['repository_usage'] as $repo) {
                    $markdown .= "  - `{$repo}`\n";

                    // Try to link to repository
                    if (isset($this->repositories[$repo])) {
                        $repoModels = $this->repositories[$repo]['model_usage'];
                        if (!empty($repoModels)) {
                            $markdown .= "    - ↓ Queries models: " . implode(', ', array_map(fn($m) => "`{$m}`", $repoModels)) . "\n";
                        }
                    }
                }
            }

            if (!empty($service['model_usage'])) {
                $markdown .= "- **Direct Model Usage:**\n";
                foreach ($service['model_usage'] as $model) {
                    $markdown .= "  - `{$model}`\n";
                }
            }

            if (!empty($service['external_api_calls'])) {
                $markdown .= "- **External API Calls:**\n";
                foreach ($service['external_api_calls'] as $api) {
                    $markdown .= "  - {$api}\n";
                }
            }

            $markdown .= "\n";
        }

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function generateRepositorySection(): string
    {
        $markdown = "## 🗄️ Repositories\n\n";

        if (empty($this->repositories)) {
            $markdown .= "*No repositories found.*\n\n";
        } else {
            foreach ($this->repositories as $repository) {
                $markdown .= "### {$repository['name']}\n\n";
                $markdown .= "- **File:** `{$repository['file']}`\n";

                if (!empty($repository['model_usage'])) {
                    $markdown .= "- **Models Used:**\n";
                    foreach ($repository['model_usage'] as $model) {
                        $markdown .= "  - `{$model}`\n";
                    }
                }

                $markdown .= "\n";
            }
        }

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function generatePlatformIntegrationSection(): string
    {
        $markdown = "## 🔌 Platform Integration Flows\n\n";

        // Find platform-related services
        $platformServices = array_filter($this->services, function ($service) {
            return str_contains($service['name'], 'Meta') ||
                str_contains($service['name'], 'Google') ||
                str_contains($service['name'], 'TikTok') ||
                str_contains($service['name'], 'LinkedIn') ||
                str_contains($service['name'], 'Twitter') ||
                str_contains($service['name'], 'Snapchat') ||
                str_contains($service['name'], 'Connector') ||
                str_contains($service['file'], 'Services/Platform');
        });

        if (empty($platformServices)) {
            $markdown .= "*No platform integration services found.*\n\n";
        } else {
            foreach ($platformServices as $service) {
                $markdown .= "### {$service['name']}\n\n";
                $markdown .= "- **File:** `{$service['file']}`\n";

                if (!empty($service['external_api_calls'])) {
                    $markdown .= "- **External API Calls:**\n";
                    foreach ($service['external_api_calls'] as $api) {
                        $markdown .= "  - {$api}\n";
                    }
                }

                if (!empty($service['dependencies'])) {
                    $markdown .= "- **Dependencies:**\n";
                    foreach ($service['dependencies'] as $dep) {
                        $markdown .= "  - `{$dep}`\n";
                    }
                }

                $markdown .= "\n";
            }
        }

        $markdown .= "---\n\n";

        return $markdown;
    }

    protected function appendDiscoveryCommands(): string
    {
        $markdown = "## 🔍 Discovery Commands\n\n";
        $markdown .= "*Use these commands to discover service layer connections:*\n\n";

        $markdown .= "### Find All Services\n\n";
        $markdown .= "```bash\n";
        $markdown .= "find app/Services -name '*.php' -type f\n";
        $markdown .= "```\n\n";

        $markdown .= "### Find All Repositories\n\n";
        $markdown .= "```bash\n";
        $markdown .= "find app/Repositories -name '*.php' -type f\n";
        $markdown .= "```\n\n";

        $markdown .= "### Find Controllers Using ApiResponse\n\n";
        $markdown .= "```bash\n";
        $markdown .= "grep -r \"use ApiResponse\" app/Http/Controllers | wc -l\n";
        $markdown .= "```\n\n";

        $markdown .= "### Find Service Dependencies\n\n";
        $markdown .= "```bash\n";
        $markdown .= "grep -A 10 \"__construct\" app/Services/*.php\n";
        $markdown .= "```\n\n";

        $markdown .= "### Find External API Calls\n\n";
        $markdown .= "```bash\n";
        $markdown .= "grep -r \"Http::\\|Guzzle\\|curl_\" app/Services\n";
        $markdown .= "```\n\n";

        return $markdown;
    }

    // Helper methods

    protected function extractDependencies(string $content): array
    {
        $dependencies = [];

        if (preg_match('/__construct\s*\(([^)]*)\)/s', $content, $matches)) {
            $params = $matches[1];

            // Extract type-hinted dependencies
            if (preg_match_all('/(protected|public|private)?\s*([A-Z][a-zA-Z0-9_\\\\]*)\s+\$\w+/s', $params, $typeMatches)) {
                foreach ($typeMatches[2] as $type) {
                    $dependencies[] = trim($type);
                }
            }
        }

        return array_unique($dependencies);
    }

    protected function extractRepositoryUsage(string $content): array
    {
        $repositories = [];

        if (preg_match_all('/([A-Z][a-zA-Z0-9_]*Repository)/', $content, $matches)) {
            $repositories = array_unique($matches[1]);
        }

        return array_values($repositories);
    }

    protected function extractModelUsage(string $content): array
    {
        $models = [];

        // Look for use statements
        if (preg_match_all('/use\s+App\\\\Models\\\\([^;]+);/', $content, $matches)) {
            foreach ($matches[1] as $model) {
                $parts = explode('\\', $model);
                $models[] = end($parts);
            }
        }

        return array_unique($models);
    }

    protected function extractExternalAPICalls(string $content): array
    {
        $apis = [];

        // HTTP facade calls
        if (str_contains($content, 'Http::')) {
            $apis[] = 'Laravel HTTP Client (Http::)';
        }

        // Guzzle
        if (str_contains($content, 'Guzzle') || str_contains($content, 'GuzzleHttp')) {
            $apis[] = 'Guzzle HTTP Client';
        }

        // cURL
        if (str_contains($content, 'curl_')) {
            $apis[] = 'cURL';
        }

        // Specific platform APIs
        if (preg_match('/graph\.facebook\.com|developers\.facebook\.com/', $content)) {
            $apis[] = 'Meta Graph API';
        }

        if (preg_match('/googleapis\.com|googleads\.googleapis/', $content)) {
            $apis[] = 'Google Ads API';
        }

        if (preg_match('/tiktok\.com|business-api\.tiktok/', $content)) {
            $apis[] = 'TikTok Business API';
        }

        return array_unique($apis);
    }

    protected function inferRoutes(string $controllerName): string
    {
        // Remove "Controller" suffix
        $base = str_replace('Controller', '', $controllerName);

        // Convert to snake_case
        $base = strtolower(preg_replace('/(?<!^)[A-Z]/', '_$0', $base));

        return "/api/{$base}/*";
    }

    protected function extractClassName(string $fullClassName): string
    {
        $parts = explode('\\', $fullClassName);
        return end($parts);
    }
}
