# Auto-assign reviewers configuration

# Add reviewers to pull requests
addReviewers: true

# Add assignees to pull requests
addAssignees: false

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - MarketingLimited

# A number of reviewers added to the pull request
numberOfReviewers: 1

# A list of assignees, overrides reviewers if set
# assignees:
#   - MarketingLimited

# A number of assignees to add to the pull request
# numberOfAssignees: 1

# Set to true to add reviewers from different groups to pull requests
# useReviewGroups: false

# A list of review groups. Review groups are used to select reviewers from different teams
# reviewGroups:
#   backend:
#     - backend-developer-1
#     - backend-developer-2
#   frontend:
#     - frontend-developer-1
#     - frontend-developer-2

# Set to true to add assignees from different groups to pull requests
# useAssigneeGroups: false

# A list of assignee groups. Assignee groups are used to select assignees from different teams
# assigneeGroups:
#   backend:
#     - backend-developer-1
#   frontend:
#     - frontend-developer-1

# Set to author to add PR creator as assignee
# addAssignees: author

skipKeywords:
  - wip
  - WIP
  - draft
