CREATE INDEX ad_variants_campaign_active_idx ON cmis.ad_variants USING btree (campaign_id, is_active);
CREATE INDEX ad_variants_campaign_winner_idx ON cmis.ad_variants USING btree (campaign_id, is_winner);
CREATE INDEX audience_templates_org_name_idx ON cmis.audience_templates USING btree (org_id, name);
CREATE INDEX cmis_ad_variants_campaign_id_index ON cmis.ad_variants USING btree (campaign_id);
CREATE INDEX cmis_audience_templates_org_id_index ON cmis.audience_templates USING btree (org_id);
CREATE INDEX cmis_inbox_items_assigned_to_index ON cmis.inbox_items USING btree (assigned_to);
CREATE INDEX cmis_inbox_items_org_id_index ON cmis.inbox_items USING btree (org_id);
CREATE INDEX cmis_inbox_items_social_account_id_index ON cmis.inbox_items USING btree (social_account_id);
CREATE INDEX cmis_post_approvals_assigned_to_index ON cmis.post_approvals USING btree (assigned_to);
CREATE INDEX cmis_post_approvals_post_id_index ON cmis.post_approvals USING btree (post_id);
CREATE INDEX cmis_post_approvals_status_index ON cmis.post_approvals USING btree (status);
CREATE INDEX cmis_publishing_queues_org_id_index ON cmis.publishing_queues USING btree (org_id);
CREATE INDEX cmis_publishing_queues_social_account_id_index ON cmis.publishing_queues USING btree (social_account_id);
CREATE INDEX cmis_scheduled_social_posts_org_id_created_at_index ON cmis.scheduled_social_posts USING btree (org_id, created_at);
CREATE INDEX cmis_scheduled_social_posts_org_id_index ON cmis.scheduled_social_posts USING btree (org_id);
CREATE INDEX cmis_scheduled_social_posts_org_id_scheduled_at_index ON cmis.scheduled_social_posts USING btree (org_id, scheduled_at);
CREATE INDEX cmis_scheduled_social_posts_org_id_status_index ON cmis.scheduled_social_posts USING btree (org_id, status);
CREATE INDEX cmis_scheduled_social_posts_scheduled_at_index ON cmis.scheduled_social_posts USING btree (scheduled_at);
CREATE INDEX cmis_scheduled_social_posts_status_index ON cmis.scheduled_social_posts USING btree (status);
CREATE INDEX idx_ab_test_variations_entity ON cmis.ab_test_variations USING btree (entity_id);
CREATE INDEX idx_ab_test_variations_test ON cmis.ab_test_variations USING btree (ab_test_id);
CREATE INDEX idx_ab_tests_ad_account ON cmis.ab_tests USING btree (ad_account_id);
CREATE INDEX idx_ab_tests_entity ON cmis.ab_tests USING btree (entity_type, entity_id);
CREATE INDEX idx_ab_tests_status ON cmis.ab_tests USING btree (test_status);
CREATE INDEX idx_ad_audiences_entity ON cmis.ad_audiences USING btree (entity_level, entity_external_id);
CREATE INDEX idx_ad_audiences_platform ON cmis.ad_audiences USING btree (platform);
CREATE INDEX idx_ad_metrics_date ON cmis.ad_metrics USING btree (date_start, date_stop);
CREATE INDEX idx_ad_metrics_entity ON cmis.ad_metrics USING btree (entity_level, entity_external_id);
CREATE INDEX idx_ai_actions_org ON cmis.ai_actions USING btree (org_id);
CREATE INDEX idx_ai_actions_org_time ON cmis.ai_actions USING btree (org_id, created_at);
CREATE INDEX idx_anchors_code ON cmis.anchors USING gist (code);
CREATE INDEX idx_api_keys_service_code ON cmis.api_keys USING btree (service_code);
CREATE INDEX idx_assets_campaign ON cmis.creative_assets USING btree (campaign_id);
CREATE INDEX idx_audit_log_ts ON cmis.audit_log USING btree (ts DESC);
CREATE INDEX idx_campaign_links_active ON cmis.campaign_context_links USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_campaign_links_campaign ON cmis.campaign_context_links USING btree (campaign_id);
CREATE INDEX idx_campaign_links_context ON cmis.campaign_context_links USING btree (context_id);
CREATE INDEX idx_campaign_links_created_at ON cmis.campaign_context_links USING btree (created_at);
CREATE INDEX idx_campaign_links_effective ON cmis.campaign_context_links USING btree (effective_from, effective_to) WHERE ((effective_from IS NOT NULL) OR (effective_to IS NOT NULL));
CREATE INDEX idx_campaign_links_link_type ON cmis.campaign_context_links USING btree (link_type);
CREATE INDEX idx_campaign_links_metadata ON cmis.campaign_context_links USING gin (metadata);
CREATE INDEX idx_campaign_links_metadata_gin ON cmis.campaign_context_links USING gin (metadata jsonb_path_ops);
CREATE INDEX idx_campaign_links_type ON cmis.campaign_context_links USING btree (context_type);
CREATE INDEX idx_campaign_offerings_cid ON cmis.campaign_offerings USING btree (campaign_id);
CREATE INDEX idx_campaign_offerings_oid ON cmis.campaign_offerings USING btree (offering_id);
CREATE INDEX idx_campaigns_active ON cmis.campaigns USING btree (org_id, status) WHERE (deleted_at IS NULL);
CREATE INDEX idx_campaigns_dates ON cmis.campaigns USING btree (start_date, end_date);
CREATE INDEX idx_campaigns_org_id ON cmis.campaigns USING btree (org_id);
CREATE INDEX idx_campaigns_org_status_created ON cmis.campaigns USING btree (org_id, status, created_at DESC);
CREATE INDEX idx_cc_channel ON cmis.copy_components USING btree (channel_id);
CREATE INDEX idx_cc_content_trgm ON cmis.copy_components USING gin (content public.gin_trgm_ops);
CREATE INDEX idx_cc_industry ON cmis.copy_components USING btree (industry_id);
CREATE INDEX idx_cc_market ON cmis.copy_components USING btree (market_id);
CREATE INDEX idx_cc_type ON cmis.copy_components USING btree (type_code);
CREATE INDEX idx_content_items_active ON cmis.content_items USING btree (org_id, created_at DESC) WHERE (deleted_at IS NULL);
CREATE INDEX idx_content_items_channel ON cmis.content_items USING btree (channel_id);
CREATE INDEX idx_content_items_context ON cmis.content_items USING btree (context_id);
CREATE INDEX idx_content_items_creative_context ON cmis.content_items USING btree (creative_context_id) WHERE (deleted_at IS NULL);
CREATE INDEX idx_content_items_example ON cmis.content_items USING btree (example_id);
CREATE INDEX idx_content_items_format ON cmis.content_items USING btree (format_id);
CREATE INDEX idx_content_items_plan ON cmis.content_items USING btree (plan_id);
CREATE INDEX idx_content_plans_org ON cmis.content_plans USING btree (org_id) WHERE (deleted_at IS NULL);
CREATE INDEX idx_contexts_metadata_gin ON cmis.contexts USING gin (metadata jsonb_path_ops);
CREATE INDEX idx_creative_assets_active ON cmis.creative_assets USING btree (org_id, campaign_id) WHERE (deleted_at IS NULL);
CREATE INDEX idx_creative_assets_org_id ON cmis.creative_assets USING btree (org_id);
CREATE INDEX idx_creative_briefs_org_id ON cmis.creative_briefs USING btree (org_id);
CREATE INDEX idx_field_value_text ON cmis.field_values USING gin (((value)::text) public.gin_trgm_ops);
CREATE INDEX idx_field_values_created ON cmis.field_values USING btree (created_at DESC);
CREATE INDEX idx_field_values_json ON cmis.field_values USING gin (value jsonb_path_ops);
CREATE INDEX idx_integrations_active ON cmis.integrations USING btree (org_id) WHERE (deleted_at IS NULL);
CREATE INDEX idx_orgs_id ON cmis.orgs USING btree (org_id);
CREATE INDEX idx_performance_metrics_campaign_time ON cmis.performance_metrics USING btree (campaign_id, observed_at DESC) WHERE (deleted_at IS NULL);
CREATE INDEX idx_reference_entities_metadata_gin ON cmis.reference_entities USING gin (metadata jsonb_path_ops);
CREATE INDEX idx_scheduled_posts_status_time ON cmis.scheduled_social_posts USING btree (status, scheduled_at) WHERE (deleted_at IS NULL);
CREATE INDEX idx_scheduled_reports_entity ON cmis.scheduled_reports USING btree (entity_id);
CREATE INDEX idx_scheduled_reports_next_run ON cmis.scheduled_reports USING btree (next_run_at) WHERE (is_active = true);
CREATE INDEX idx_scheduled_reports_type ON cmis.scheduled_reports USING btree (report_type);
CREATE INDEX idx_security_audit_org_created ON cmis.security_context_audit USING btree (org_id, created_at DESC);
CREATE INDEX idx_security_audit_user_created ON cmis.security_context_audit USING btree (user_id, created_at DESC);
CREATE INDEX idx_team_account_access_user_social ON cmis.team_account_access USING btree (org_user_id, social_account_id);
CREATE INDEX idx_team_invitations_email ON cmis.team_invitations USING btree (invited_email);
CREATE INDEX idx_team_invitations_org_status ON cmis.team_invitations USING btree (org_id, status);
CREATE INDEX idx_user_orgs_role ON cmis.user_orgs USING btree (role_id);
CREATE INDEX idx_user_sessions_expires ON cmis.user_sessions USING btree (expires_at) WHERE (is_active = true);
CREATE INDEX idx_user_sessions_token ON cmis.user_sessions USING btree (session_token) WHERE (is_active = true);
CREATE INDEX idx_user_sessions_user_id ON cmis.user_sessions USING btree (user_id);
CREATE INDEX idx_users_email ON cmis.users USING btree (email);
CREATE INDEX idx_values_context ON cmis.field_values USING btree (context_id);
CREATE INDEX idx_values_field ON cmis.field_values USING btree (field_id);
CREATE INDEX idx_video_scenes_asset ON cmis.video_scenes USING btree (asset_id);
CREATE INDEX inbox_items_assignee_status_idx ON cmis.inbox_items USING btree (assigned_to, status);
CREATE INDEX inbox_items_needs_reply_idx ON cmis.inbox_items USING btree (needs_reply, status);
CREATE INDEX inbox_items_org_status_idx ON cmis.inbox_items USING btree (org_id, status);
CREATE INDEX inbox_items_platform_external_idx ON cmis.inbox_items USING btree (platform, external_id);
CREATE INDEX jobs_queue_index ON cmis.jobs USING btree (queue);
CREATE INDEX post_approvals_post_status_idx ON cmis.post_approvals USING btree (post_id, status);
CREATE INDEX post_approvals_status_assignee_idx ON cmis.post_approvals USING btree (status, assigned_to);
CREATE INDEX sessions_last_activity_index ON cmis.sessions USING btree (last_activity);
CREATE INDEX sessions_user_id_index ON cmis.sessions USING btree (user_id);
CREATE INDEX idx_prompt_templates_trgm ON cmis_analytics.prompt_templates USING gin (prompt_text public.gin_trgm_ops);
CREATE UNIQUE INDEX uq_perf_snapshot ON cmis_analytics.performance_snapshot USING btree (org_id, campaign_id, kpi, observed_at);
CREATE INDEX idx_audit_logs_created ON cmis_audit.logs USING btree (created_at);
CREATE INDEX idx_dev_logs_task ON cmis_dev.dev_logs USING btree (task_id);
CREATE INDEX idx_dev_tasks_status ON cmis_dev.dev_tasks USING btree (status);
CREATE INDEX idx_creative_content_embedding ON cmis_knowledge.creative_templates USING hnsw (content_embedding public.vector_cosine_ops);
CREATE INDEX idx_dev_content_embedding ON cmis_knowledge.dev USING hnsw (content_embedding public.vector_cosine_ops);
CREATE INDEX idx_dev_content_embedding_hnsw ON cmis_knowledge.dev USING hnsw (content_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_dev_semantic_summary_embedding_hnsw ON cmis_knowledge.dev USING hnsw (semantic_summary_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_dev_semantic_summary_hnsw ON cmis_knowledge.dev USING hnsw (semantic_summary_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_direction_embedding ON cmis_knowledge.direction_mappings USING hnsw (direction_embedding public.vector_cosine_ops);
CREATE INDEX idx_direction_mappings_metadata_gin ON cmis_knowledge.direction_mappings USING gin (metadata jsonb_path_ops);
CREATE INDEX idx_embedding_queue_status ON cmis_knowledge.embedding_update_queue USING btree (status, priority DESC) WHERE (status = ANY (ARRAY['pending'::text, 'processing'::text]));
CREATE UNIQUE INDEX idx_embeddings_cache_hash ON cmis_knowledge.embeddings_cache USING btree (input_hash);
CREATE INDEX idx_embeddings_cache_last_used ON cmis_knowledge.embeddings_cache USING btree (last_used_at);
CREATE INDEX idx_embeddings_cache_metadata_gin ON cmis_knowledge.embeddings_cache USING gin (metadata jsonb_path_ops);
CREATE INDEX idx_embeddings_cache_source ON cmis_knowledge.embeddings_cache USING btree (source_table, source_id);
CREATE INDEX idx_embeddings_cache_vector ON cmis_knowledge.embeddings_cache USING hnsw (embedding public.vector_cosine_ops);
CREATE INDEX idx_index_direction_vector ON cmis_knowledge.index USING hnsw (direction_vector public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_index_direction_vector_hnsw ON cmis_knowledge.index USING hnsw (direction_vector public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_index_intent_vector ON cmis_knowledge.index USING hnsw (intent_vector public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_index_intent_vector_hnsw ON cmis_knowledge.index USING hnsw (intent_vector public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_index_keywords_embedding_hnsw ON cmis_knowledge.index USING hnsw (keywords_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_index_purpose_vector ON cmis_knowledge.index USING hnsw (purpose_vector public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_index_purpose_vector_hnsw ON cmis_knowledge.index USING hnsw (purpose_vector public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_index_topic_embedding ON cmis_knowledge.index USING hnsw (topic_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_index_topic_embedding_hnsw ON cmis_knowledge.index USING hnsw (topic_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_intent_embedding ON cmis_knowledge.intent_mappings USING hnsw (intent_embedding public.vector_cosine_ops);
CREATE INDEX idx_knowledge_content_search ON cmis_knowledge.dev USING gin (content_search);
CREATE INDEX idx_knowledge_domain_tier ON cmis_knowledge.index USING btree (domain, category, tier);
CREATE INDEX idx_knowledge_index_direction_vector ON cmis_knowledge.index USING ivfflat (direction_vector public.vector_cosine_ops) WITH (lists='200');
CREATE INDEX idx_knowledge_index_intent_vector ON cmis_knowledge.index USING ivfflat (intent_vector public.vector_cosine_ops) WITH (lists='200');
CREATE INDEX idx_knowledge_index_keywords_embedding ON cmis_knowledge.index USING ivfflat (keywords_embedding public.vector_cosine_ops) WITH (lists='200');
CREATE INDEX idx_knowledge_index_purpose_vector ON cmis_knowledge.index USING ivfflat (purpose_vector public.vector_cosine_ops) WITH (lists='200');
CREATE INDEX idx_knowledge_index_topic_embedding ON cmis_knowledge.index USING ivfflat (topic_embedding public.vector_cosine_ops) WITH (lists='200');
CREATE INDEX idx_knowledge_last_verified ON cmis_knowledge.index USING btree (last_verified_at DESC);
CREATE INDEX idx_marketing_audience_embedding ON cmis_knowledge.marketing USING hnsw (audience_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_marketing_audience_embedding_hnsw ON cmis_knowledge.marketing USING hnsw (audience_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_marketing_campaign_intent_vector_hnsw ON cmis_knowledge.marketing USING hnsw (campaign_intent_vector public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_marketing_content_embedding ON cmis_knowledge.marketing USING hnsw (content_embedding public.vector_cosine_ops);
CREATE INDEX idx_marketing_content_embedding_hnsw ON cmis_knowledge.marketing USING hnsw (content_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_marketing_emotional_direction_vector_hnsw ON cmis_knowledge.marketing USING hnsw (emotional_direction_vector public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_marketing_tone_embedding ON cmis_knowledge.marketing USING hnsw (tone_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_marketing_tone_embedding_hnsw ON cmis_knowledge.marketing USING hnsw (tone_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_purpose_embedding ON cmis_knowledge.purpose_mappings USING hnsw (purpose_embedding public.vector_cosine_ops);
CREATE INDEX idx_research_content_embedding ON cmis_knowledge.research USING hnsw (content_embedding public.vector_cosine_ops);
CREATE INDEX idx_research_content_embedding_hnsw ON cmis_knowledge.research USING hnsw (content_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_research_insight_embedding ON cmis_knowledge.research USING hnsw (insight_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_research_insight_embedding_hnsw ON cmis_knowledge.research USING hnsw (insight_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_research_research_direction_vector_hnsw ON cmis_knowledge.research USING hnsw (research_direction_vector public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_research_source_context_embedding_hnsw ON cmis_knowledge.research USING hnsw (source_context_embedding public.vector_cosine_ops) WITH (m='16', ef_construction='64');
CREATE INDEX idx_search_cache_hash ON cmis_knowledge.semantic_search_results_cache USING btree (query_hash);
CREATE INDEX idx_search_logs_time ON cmis_knowledge.semantic_search_logs USING btree (created_at DESC);
CREATE INDEX idx_examples_body_fts ON lab.example_sets USING gin (((body)::text) public.gin_trgm_ops);
CREATE INDEX idx_examples_tags ON lab.example_sets USING gin (tags);
CREATE INDEX idx_audit_action ON operations.audit_log USING btree (action);
CREATE INDEX idx_audit_changed_fields ON operations.audit_log USING gin (changed_fields);
CREATE INDEX idx_audit_ip ON operations.audit_log USING btree (ip_address);
CREATE INDEX idx_audit_log_metadata_gin ON operations.audit_log USING gin (metadata jsonb_path_ops);
CREATE INDEX idx_audit_metadata ON operations.audit_log USING gin (metadata);
CREATE INDEX idx_audit_record ON operations.audit_log USING btree (record_id);
CREATE INDEX idx_audit_record_key ON operations.audit_log USING btree (record_key);
CREATE INDEX idx_audit_session ON operations.audit_log USING btree (session_id);
CREATE INDEX idx_audit_table ON operations.audit_log USING btree (table_schema, table_name);
CREATE INDEX idx_audit_tags ON operations.audit_log USING gin (tags);
CREATE INDEX idx_audit_timestamp ON operations.audit_log USING btree ("timestamp");
CREATE INDEX idx_audit_timestamp_hour ON operations.audit_log USING btree (date_trunc('hour'::text, "timestamp"));
CREATE INDEX idx_audit_user ON operations.audit_log USING btree (user_id);
CREATE INDEX idx_audit_username ON operations.audit_log USING btree (username);
CREATE INDEX idx_migrations_phase ON operations.migrations USING btree (phase);
CREATE INDEX idx_migrations_started ON operations.migrations USING btree (started_at);
CREATE INDEX idx_migrations_status ON operations.migrations USING btree (status);
