ALTER TABLE ONLY archive.backup_integrations_cmis ALTER COLUMN id SET DEFAULT nextval('archive.backup_integrations_cmis_id_seq'::regclass);   -- -- Name: embedding_update_queue_backup id; Type: DEFAULT; Schema: archive; Owner: begin --  ALTER TABLE ONLY archive.embedding_update_queue_backup ALTER COLUMN id SET DEFAULT nextval('archive.embedding_update_queue_backup_id_seq'::regclass);
ALTER TABLE ONLY cmis.ad_metrics ALTER COLUMN id SET DEFAULT nextval('cmis.ad_metrics_id_seq'::regclass);   -- -- Name: failed_jobs id; Type: DEFAULT; Schema: cmis; Owner: begin --  ALTER TABLE ONLY cmis.failed_jobs ALTER COLUMN id SET DEFAULT nextval('cmis.failed_jobs_id_seq'::regclass);
ALTER TABLE ONLY cmis.jobs ALTER COLUMN id SET DEFAULT nextval('cmis.jobs_id_seq'::regclass);   -- -- Name: meta_field_dictionary id; Type: DEFAULT; Schema: cmis; Owner: begin --  ALTER TABLE ONLY cmis.meta_field_dictionary ALTER COLUMN id SET DEFAULT nextval('cmis.meta_field_dictionary_id_seq'::regclass);
ALTER TABLE ONLY cmis.meta_function_descriptions ALTER COLUMN id SET DEFAULT nextval('cmis.meta_function_descriptions_id_seq'::regclass);   -- -- Name: migrations id; Type: DEFAULT; Schema: cmis; Owner: begin --  ALTER TABLE ONLY cmis.migrations ALTER COLUMN id SET DEFAULT nextval('cmis.migrations_id_seq'::regclass);
ALTER TABLE ONLY cmis.modules ALTER COLUMN module_id SET DEFAULT nextval('cmis.modules_module_id_seq'::regclass);   -- -- Name: naming_templates naming_id; Type: DEFAULT; Schema: cmis; Owner: begin --  ALTER TABLE ONLY cmis.naming_templates ALTER COLUMN naming_id SET DEFAULT nextval('cmis.naming_templates_naming_id_seq'::regclass);
-- Name: dev id; Type: DEFAULT; Schema: cmis_knowledge; Owner: begin --  ALTER TABLE ONLY cmis_knowledge.dev ALTER COLUMN id SET DEFAULT nextval('cmis_knowledge.dev_id_seq'::regclass);
ALTER TABLE ONLY cmis_knowledge.index_backup_2025_11_10 ALTER COLUMN id SET DEFAULT nextval('cmis_knowledge.index_backup_2025_11_10_id_seq'::regclass);   -- -- Name: marketing id; Type: DEFAULT; Schema: cmis_knowledge; Owner: begin --  ALTER TABLE ONLY cmis_knowledge.marketing ALTER COLUMN id SET DEFAULT nextval('cmis_knowledge.marketing_id_seq'::regclass);
ALTER TABLE ONLY cmis_knowledge.org ALTER COLUMN id SET DEFAULT nextval('cmis_knowledge.org_id_seq'::regclass);   -- -- Name: research id; Type: DEFAULT; Schema: cmis_knowledge; Owner: begin --  ALTER TABLE ONLY cmis_knowledge.research ALTER COLUMN id SET DEFAULT nextval('cmis_knowledge.research_id_seq'::regclass);
ALTER TABLE ONLY operations.audit_log ALTER COLUMN id SET DEFAULT nextval('operations.audit_log_id_seq'::regclass);   -- -- Name: fix_tracking fix_id; Type: DEFAULT; Schema: operations; Owner: begin --  ALTER TABLE ONLY operations.fix_tracking ALTER COLUMN fix_id SET DEFAULT nextval('operations.fix_tracking_fix_id_seq'::regclass);
ALTER TABLE ONLY operations.migrations ALTER COLUMN migration_id SET DEFAULT nextval('operations.migrations_migration_id_seq'::regclass);   -- -- Name: channel_formats format_id; Type: DEFAULT; Schema: public; Owner: begin --  ALTER TABLE ONLY public.channel_formats ALTER COLUMN format_id SET DEFAULT nextval('public.channel_formats_format_id_seq'::regclass);
ALTER TABLE ONLY public.channels ALTER COLUMN channel_id SET DEFAULT nextval('public.channels_channel_id_seq'::regclass);   -- -- Name: industries industry_id; Type: DEFAULT; Schema: public; Owner: begin --  ALTER TABLE ONLY public.industries ALTER COLUMN industry_id SET DEFAULT nextval('public.industries_industry_id_seq'::regclass);
ALTER TABLE ONLY public.jobs ALTER COLUMN id SET DEFAULT nextval('public.jobs_id_seq'::regclass);   -- -- Name: markets market_id; Type: DEFAULT; Schema: public; Owner: begin --  ALTER TABLE ONLY public.markets ALTER COLUMN market_id SET DEFAULT nextval('public.markets_market_id_seq'::regclass);
ALTER TABLE ONLY public.migration_log ALTER COLUMN id SET DEFAULT nextval('public.migration_log_id_seq'::regclass);   -- -- Name: modules_old module_id; Type: DEFAULT; Schema: public; Owner: begin --  ALTER TABLE ONLY public.modules_old ALTER COLUMN module_id SET DEFAULT nextval('public.modules_module_id_seq'::regclass);
ALTER TABLE ONLY public.naming_templates_old ALTER COLUMN naming_id SET DEFAULT nextval('public.naming_templates_naming_id_seq'::regclass);   -- -- Name: visual_kpis kpi_id; Type: DEFAULT; Schema: public; Owner: begin --  ALTER TABLE ONLY public.visual_kpis ALTER COLUMN kpi_id SET DEFAULT nextval('public.visual_kpis_kpi_id_seq'::regclass);
ALTER TABLE ONLY public.visual_principles ALTER COLUMN principle_id SET DEFAULT nextval('public.visual_principles_principle_id_seq'::regclass);   -- -- Name: visual_recommendations recommendation_id; Type: DEFAULT; Schema: public; Owner: begin --  ALTER TABLE ONLY public.visual_recommendations ALTER COLUMN recommendation_id SET DEFAULT nextval('public.visual_recommendations_recommendation_id_seq'::regclass);
ALTER TABLE ONLY archive.backup_integrations_cmis     ADD CONSTRAINT backup_integrations_cmis_pkey PRIMARY KEY (id);
ALTER TABLE ONLY archive.embedding_update_queue_backup     ADD CONSTRAINT embedding_update_queue_backup_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.ab_test_variations     ADD CONSTRAINT ab_test_variations_pkey PRIMARY KEY (variation_id);
ALTER TABLE ONLY cmis.ab_tests     ADD CONSTRAINT ab_tests_pkey PRIMARY KEY (ab_test_id);
ALTER TABLE ONLY cmis.ad_accounts     ADD CONSTRAINT ad_accounts_integration_id_account_external_id_key UNIQUE (integration_id, account_external_id);
ALTER TABLE ONLY cmis.ad_accounts     ADD CONSTRAINT ad_accounts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.ad_audiences     ADD CONSTRAINT ad_audiences_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.ad_campaigns     ADD CONSTRAINT ad_campaigns_integration_id_campaign_external_id_key UNIQUE (integration_id, campaign_external_id);
ALTER TABLE ONLY cmis.ad_campaigns     ADD CONSTRAINT ad_campaigns_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.ad_entities     ADD CONSTRAINT ad_entities_integration_id_ad_external_id_key UNIQUE (integration_id, ad_external_id);
ALTER TABLE ONLY cmis.ad_entities     ADD CONSTRAINT ad_entities_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.ad_metrics     ADD CONSTRAINT ad_metrics_integration_id_entity_level_entity_external_id_d_key UNIQUE (integration_id, entity_level, entity_external_id, date_start, date_stop);
ALTER TABLE ONLY cmis.ad_metrics     ADD CONSTRAINT ad_metrics_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.ad_sets     ADD CONSTRAINT ad_sets_integration_id_adset_external_id_key UNIQUE (integration_id, adset_external_id);
ALTER TABLE ONLY cmis.ad_sets     ADD CONSTRAINT ad_sets_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.ad_variants     ADD CONSTRAINT ad_variants_pkey PRIMARY KEY (variant_id);
ALTER TABLE ONLY cmis.ai_actions     ADD CONSTRAINT ai_actions_pkey PRIMARY KEY (action_id);
ALTER TABLE ONLY cmis.ai_generated_campaigns     ADD CONSTRAINT ai_generated_campaigns_pkey PRIMARY KEY (campaign_id);
ALTER TABLE ONLY cmis.ai_models     ADD CONSTRAINT ai_models_pkey PRIMARY KEY (model_id);
ALTER TABLE ONLY cmis.analytics_integrations     ADD CONSTRAINT analytics_integrations_pkey PRIMARY KEY (integration_id);
ALTER TABLE ONLY cmis.anchors     ADD CONSTRAINT anchors_code_key UNIQUE (code);
ALTER TABLE ONLY cmis.anchors     ADD CONSTRAINT anchors_pkey PRIMARY KEY (anchor_id);
ALTER TABLE ONLY cmis.api_keys     ADD CONSTRAINT api_keys_pkey PRIMARY KEY (key_id);
ALTER TABLE ONLY cmis.api_keys     ADD CONSTRAINT api_keys_service_code_key UNIQUE (service_code);
ALTER TABLE ONLY cmis.audience_templates     ADD CONSTRAINT audience_templates_pkey PRIMARY KEY (template_id);
ALTER TABLE ONLY cmis.audio_templates     ADD CONSTRAINT audio_templates_pkey PRIMARY KEY (atpl_id);
ALTER TABLE ONLY cmis.audit_log     ADD CONSTRAINT audit_log_pkey PRIMARY KEY (log_id);
ALTER TABLE ONLY cmis.bundle_offerings     ADD CONSTRAINT bundle_offerings_pkey PRIMARY KEY (bundle_id, offering_id);
ALTER TABLE ONLY cmis.cache_locks     ADD CONSTRAINT cache_locks_pkey PRIMARY KEY (key);
ALTER TABLE ONLY cmis.cache_metadata     ADD CONSTRAINT cache_metadata_pkey PRIMARY KEY (cache_name);
ALTER TABLE ONLY cmis.cache     ADD CONSTRAINT cache_pkey PRIMARY KEY (key);
ALTER TABLE ONLY cmis.campaign_context_links     ADD CONSTRAINT campaign_context_links_campaign_id_context_id_link_type_key UNIQUE (campaign_id, context_id, link_type);
ALTER TABLE ONLY cmis.campaign_context_links     ADD CONSTRAINT campaign_context_links_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.campaign_offerings     ADD CONSTRAINT campaign_offerings_pkey PRIMARY KEY (campaign_id, offering_id);
ALTER TABLE ONLY cmis.campaign_performance_dashboard     ADD CONSTRAINT campaign_performance_dashboard_pkey PRIMARY KEY (dashboard_id);
ALTER TABLE ONLY cmis.campaigns     ADD CONSTRAINT campaigns_pkey PRIMARY KEY (campaign_id);
ALTER TABLE ONLY cmis.cognitive_tracker_template     ADD CONSTRAINT cognitive_tracker_template_pkey PRIMARY KEY (tracker_id);
ALTER TABLE ONLY cmis.cognitive_trends     ADD CONSTRAINT cognitive_trends_pkey PRIMARY KEY (trend_id);
ALTER TABLE ONLY cmis.compliance_audits     ADD CONSTRAINT compliance_audits_pkey PRIMARY KEY (audit_id);
ALTER TABLE ONLY cmis.compliance_rule_channels     ADD CONSTRAINT compliance_rule_channels_pkey PRIMARY KEY (rule_id, channel_id);
ALTER TABLE ONLY cmis.compliance_rules     ADD CONSTRAINT compliance_rules_code_key UNIQUE (code);
ALTER TABLE ONLY cmis.compliance_rules     ADD CONSTRAINT compliance_rules_pkey PRIMARY KEY (rule_id);
ALTER TABLE ONLY cmis.content_items     ADD CONSTRAINT content_items_pkey PRIMARY KEY (item_id);
ALTER TABLE ONLY cmis.content_plans     ADD CONSTRAINT content_plans_pkey PRIMARY KEY (plan_id);
ALTER TABLE ONLY cmis.contexts_base     ADD CONSTRAINT contexts_base_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.contexts_creative     ADD CONSTRAINT contexts_creative_pkey PRIMARY KEY (context_id);
ALTER TABLE ONLY cmis.contexts_offering     ADD CONSTRAINT contexts_offering_pkey PRIMARY KEY (context_id);
ALTER TABLE ONLY cmis.contexts     ADD CONSTRAINT contexts_pkey PRIMARY KEY (context_id);
ALTER TABLE ONLY cmis.contexts_value     ADD CONSTRAINT contexts_value_pkey PRIMARY KEY (context_id);
ALTER TABLE ONLY cmis.copy_components     ADD CONSTRAINT copy_components_pkey PRIMARY KEY (component_id);
ALTER TABLE ONLY cmis.creative_assets     ADD CONSTRAINT creative_assets_pkey PRIMARY KEY (asset_id);
ALTER TABLE ONLY cmis.creative_briefs     ADD CONSTRAINT creative_briefs_pkey PRIMARY KEY (brief_id);
ALTER TABLE ONLY cmis.creative_contexts     ADD CONSTRAINT creative_contexts_pkey PRIMARY KEY (context_id);
ALTER TABLE ONLY cmis.creative_outputs     ADD CONSTRAINT creative_outputs_pkey PRIMARY KEY (output_id);
ALTER TABLE ONLY cmis.data_feeds     ADD CONSTRAINT data_feeds_pkey PRIMARY KEY (feed_id);
ALTER TABLE ONLY cmis.dataset_files     ADD CONSTRAINT dataset_files_pkey PRIMARY KEY (file_id);
ALTER TABLE ONLY cmis.dataset_packages     ADD CONSTRAINT dataset_packages_code_version_key UNIQUE (code, version);
ALTER TABLE ONLY cmis.dataset_packages     ADD CONSTRAINT dataset_packages_pkey PRIMARY KEY (pkg_id);
ALTER TABLE ONLY cmis.experiment_variants     ADD CONSTRAINT experiment_variants_pkey PRIMARY KEY (exp_id, asset_id);
ALTER TABLE ONLY cmis.experiments     ADD CONSTRAINT experiments_pkey PRIMARY KEY (exp_id);
ALTER TABLE ONLY cmis.export_bundle_items     ADD CONSTRAINT export_bundle_items_pkey PRIMARY KEY (bundle_id, asset_id);
ALTER TABLE ONLY cmis.export_bundles     ADD CONSTRAINT export_bundles_pkey PRIMARY KEY (bundle_id);
ALTER TABLE ONLY cmis.failed_jobs     ADD CONSTRAINT failed_jobs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.failed_jobs     ADD CONSTRAINT failed_jobs_uuid_unique UNIQUE (uuid);
ALTER TABLE ONLY cmis.feed_items     ADD CONSTRAINT feed_items_pkey PRIMARY KEY (item_id);
ALTER TABLE ONLY cmis.field_aliases     ADD CONSTRAINT field_aliases_pkey PRIMARY KEY (alias_slug);
ALTER TABLE ONLY cmis.field_definitions     ADD CONSTRAINT field_definitions_pkey PRIMARY KEY (field_id);
ALTER TABLE ONLY cmis.field_definitions     ADD CONSTRAINT field_definitions_slug_key UNIQUE (slug);
ALTER TABLE ONLY cmis.field_values     ADD CONSTRAINT field_values_field_id_context_id_key UNIQUE (field_id, context_id);
ALTER TABLE ONLY cmis.field_values     ADD CONSTRAINT field_values_pkey PRIMARY KEY (value_id);
ALTER TABLE ONLY cmis.flow_steps     ADD CONSTRAINT flow_steps_pkey PRIMARY KEY (step_id);
ALTER TABLE ONLY cmis.flows     ADD CONSTRAINT flows_name_version_org_id_key UNIQUE (name, version, org_id);
ALTER TABLE ONLY cmis.flows     ADD CONSTRAINT flows_pkey PRIMARY KEY (flow_id);
ALTER TABLE ONLY cmis.inbox_items     ADD CONSTRAINT inbox_items_pkey PRIMARY KEY (item_id);
ALTER TABLE ONLY cmis.integrations     ADD CONSTRAINT integrations_pkey PRIMARY KEY (integration_id);
ALTER TABLE ONLY cmis.job_batches     ADD CONSTRAINT job_batches_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.jobs     ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.logs_migration     ADD CONSTRAINT logs_migration_pkey PRIMARY KEY (log_id);
ALTER TABLE ONLY cmis.meta_documentation     ADD CONSTRAINT meta_documentation_meta_key_key UNIQUE (meta_key);
ALTER TABLE ONLY cmis.meta_documentation     ADD CONSTRAINT meta_documentation_pkey1 PRIMARY KEY (doc_id);
ALTER TABLE ONLY cmis.meta_field_dictionary     ADD CONSTRAINT meta_field_dictionary_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.meta_function_descriptions     ADD CONSTRAINT meta_function_descriptions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.migrations     ADD CONSTRAINT migrations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.modules     ADD CONSTRAINT modules_code_key UNIQUE (code);
ALTER TABLE ONLY cmis.modules     ADD CONSTRAINT modules_pkey PRIMARY KEY (module_id);
ALTER TABLE ONLY cmis.naming_templates     ADD CONSTRAINT naming_templates_pkey PRIMARY KEY (naming_id);
ALTER TABLE ONLY cmis.naming_templates     ADD CONSTRAINT naming_templates_scope_key UNIQUE (scope);
ALTER TABLE ONLY cmis.offerings_full_details     ADD CONSTRAINT offerings_full_details_pkey PRIMARY KEY (detail_id);
ALTER TABLE ONLY cmis.offerings_old     ADD CONSTRAINT offerings_org_id_name_key UNIQUE (org_id, name);
ALTER TABLE ONLY cmis.offerings_old     ADD CONSTRAINT offerings_pkey PRIMARY KEY (offering_id);
ALTER TABLE ONLY cmis.ops_audit     ADD CONSTRAINT ops_audit_pkey PRIMARY KEY (audit_id);
ALTER TABLE ONLY cmis.ops_etl_log     ADD CONSTRAINT ops_etl_log_pkey PRIMARY KEY (log_id);
ALTER TABLE ONLY cmis.org_datasets     ADD CONSTRAINT org_datasets_pkey PRIMARY KEY (org_id, pkg_id);
ALTER TABLE ONLY cmis.org_markets     ADD CONSTRAINT org_markets_pkey PRIMARY KEY (org_id, market_id);
ALTER TABLE ONLY cmis.orgs     ADD CONSTRAINT orgs_name_key UNIQUE (name);
ALTER TABLE ONLY cmis.orgs     ADD CONSTRAINT orgs_pkey PRIMARY KEY (org_id);
ALTER TABLE ONLY cmis.output_contracts     ADD CONSTRAINT output_contracts_code_key UNIQUE (code);
ALTER TABLE ONLY cmis.output_contracts     ADD CONSTRAINT output_contracts_pkey PRIMARY KEY (contract_id);
ALTER TABLE ONLY cmis.password_reset_tokens     ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (email);
ALTER TABLE ONLY cmis.performance_metrics     ADD CONSTRAINT performance_metrics_pkey PRIMARY KEY (metric_id);
ALTER TABLE ONLY cmis.permissions_cache     ADD CONSTRAINT permissions_cache_pkey PRIMARY KEY (permission_code);
ALTER TABLE ONLY cmis.permissions     ADD CONSTRAINT permissions_permission_code_key UNIQUE (permission_code);
ALTER TABLE ONLY cmis.permissions     ADD CONSTRAINT permissions_pkey PRIMARY KEY (permission_id);
ALTER TABLE ONLY cmis.post_approvals     ADD CONSTRAINT post_approvals_pkey PRIMARY KEY (approval_id);
ALTER TABLE ONLY cmis.predictive_visual_engine     ADD CONSTRAINT predictive_visual_engine_pkey PRIMARY KEY (prediction_id);
ALTER TABLE ONLY cmis.prompt_template_contracts     ADD CONSTRAINT prompt_template_contracts_pkey PRIMARY KEY (prompt_id, contract_id);
ALTER TABLE ONLY cmis.prompt_template_presql     ADD CONSTRAINT prompt_template_presql_pkey PRIMARY KEY (prompt_id, snippet_id);
ALTER TABLE ONLY cmis.prompt_template_required_fields     ADD CONSTRAINT prompt_template_required_fields_pkey PRIMARY KEY (prompt_id, field_id);
ALTER TABLE ONLY cmis.prompt_templates     ADD CONSTRAINT prompt_templates_name_version_key UNIQUE (name, version);
ALTER TABLE ONLY cmis.prompt_templates     ADD CONSTRAINT prompt_templates_pkey PRIMARY KEY (prompt_id);
ALTER TABLE ONLY cmis.publishing_queues     ADD CONSTRAINT publishing_queues_account_unique UNIQUE (social_account_id);
ALTER TABLE ONLY cmis.publishing_queues     ADD CONSTRAINT publishing_queues_pkey PRIMARY KEY (queue_id);
ALTER TABLE ONLY cmis.reference_entities     ADD CONSTRAINT reference_entities_pkey PRIMARY KEY (ref_id);
ALTER TABLE ONLY cmis.required_fields_cache     ADD CONSTRAINT required_fields_cache_pkey PRIMARY KEY (module_scope);
ALTER TABLE ONLY cmis.role_permissions     ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.role_permissions     ADD CONSTRAINT role_permissions_role_id_permission_id_key UNIQUE (role_id, permission_id);
ALTER TABLE ONLY cmis.roles     ADD CONSTRAINT roles_org_id_role_code_key UNIQUE (org_id, role_code);
ALTER TABLE ONLY cmis.roles     ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);
ALTER TABLE ONLY cmis.scene_library     ADD CONSTRAINT scene_library_pkey PRIMARY KEY (scene_id);
ALTER TABLE ONLY cmis.scheduled_reports     ADD CONSTRAINT scheduled_reports_pkey PRIMARY KEY (schedule_id);
ALTER TABLE ONLY cmis.scheduled_social_posts     ADD CONSTRAINT scheduled_social_posts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.security_context_audit     ADD CONSTRAINT security_context_audit_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.segments     ADD CONSTRAINT segments_org_id_name_key UNIQUE (org_id, name);
ALTER TABLE ONLY cmis.segments     ADD CONSTRAINT segments_pkey PRIMARY KEY (segment_id);
ALTER TABLE ONLY cmis.session_context     ADD CONSTRAINT session_context_pkey PRIMARY KEY (session_id);
ALTER TABLE ONLY cmis.sessions     ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.social_account_metrics     ADD CONSTRAINT social_account_metrics_pkey PRIMARY KEY (integration_id, period_start, period_end);
ALTER TABLE ONLY cmis.social_accounts     ADD CONSTRAINT social_accounts_account_id_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.social_accounts     ADD CONSTRAINT social_accounts_integration_id_key UNIQUE (integration_id);
ALTER TABLE ONLY cmis.social_post_metrics     ADD CONSTRAINT social_post_metrics_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.social_posts     ADD CONSTRAINT social_posts_integration_id_post_external_id_key UNIQUE (integration_id, post_external_id);
ALTER TABLE ONLY cmis.social_posts     ADD CONSTRAINT social_posts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.sql_snippets     ADD CONSTRAINT sql_snippets_name_key UNIQUE (name);
ALTER TABLE ONLY cmis.sql_snippets     ADD CONSTRAINT sql_snippets_pkey PRIMARY KEY (snippet_id);
ALTER TABLE ONLY cmis.sync_logs     ADD CONSTRAINT sync_logs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.team_account_access     ADD CONSTRAINT team_account_access_org_user_id_social_account_id_key UNIQUE (org_user_id, social_account_id);
ALTER TABLE ONLY cmis.team_account_access     ADD CONSTRAINT team_account_access_pkey PRIMARY KEY (access_id);
ALTER TABLE ONLY cmis.team_invitations     ADD CONSTRAINT team_invitations_pkey PRIMARY KEY (invitation_id);
ALTER TABLE ONLY cmis.campaigns     ADD CONSTRAINT uq_campaign_business UNIQUE (org_id, name, start_date);
ALTER TABLE ONLY cmis.integrations     ADD CONSTRAINT uq_integration_business UNIQUE (org_id, platform, account_id);
ALTER TABLE ONLY cmis.flow_steps     ADD CONSTRAINT uq_step UNIQUE (flow_id, ord);
ALTER TABLE ONLY cmis.user_activities     ADD CONSTRAINT user_activities_pkey PRIMARY KEY (activity_id);
ALTER TABLE ONLY cmis.user_orgs     ADD CONSTRAINT user_orgs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.user_orgs     ADD CONSTRAINT user_orgs_user_id_org_id_key UNIQUE (user_id, org_id);
ALTER TABLE ONLY cmis.user_permissions     ADD CONSTRAINT user_permissions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis.user_permissions     ADD CONSTRAINT user_permissions_user_id_org_id_permission_id_key UNIQUE (user_id, org_id, permission_id);
ALTER TABLE ONLY cmis.user_sessions     ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (session_id);
ALTER TABLE ONLY cmis.user_sessions     ADD CONSTRAINT user_sessions_session_token_key UNIQUE (session_token);
ALTER TABLE ONLY cmis.users     ADD CONSTRAINT users_email_unique UNIQUE (email);
ALTER TABLE ONLY cmis.users     ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);
ALTER TABLE ONLY cmis.value_contexts     ADD CONSTRAINT value_contexts_pkey PRIMARY KEY (context_id);
ALTER TABLE ONLY cmis.variation_policies     ADD CONSTRAINT variation_policies_pkey PRIMARY KEY (policy_id);
ALTER TABLE ONLY cmis.video_scenes     ADD CONSTRAINT video_scenes_pkey PRIMARY KEY (scene_id);
ALTER TABLE ONLY cmis.video_templates     ADD CONSTRAINT video_templates_pkey PRIMARY KEY (vtpl_id);
ALTER TABLE ONLY cmis_analytics.ai_queries     ADD CONSTRAINT ai_queries_pkey PRIMARY KEY (query_id);
ALTER TABLE ONLY cmis_analytics.migration_log     ADD CONSTRAINT migration_log_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis_analytics.performance_snapshot     ADD CONSTRAINT performance_snapshot_pkey PRIMARY KEY (snapshot_id);
ALTER TABLE ONLY cmis_analytics.prompt_templates     ADD CONSTRAINT prompt_templates_pkey PRIMARY KEY (template_id);
ALTER TABLE ONLY cmis_analytics.scheduled_jobs     ADD CONSTRAINT scheduled_jobs_pkey PRIMARY KEY (job_id);
ALTER TABLE ONLY cmis_audit.logs     ADD CONSTRAINT logs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis_dev.dev_logs     ADD CONSTRAINT dev_logs_pkey PRIMARY KEY (log_id);
ALTER TABLE ONLY cmis_dev.dev_tasks     ADD CONSTRAINT dev_tasks_pkey PRIMARY KEY (task_id);
ALTER TABLE ONLY cmis_knowledge.cognitive_manifest     ADD CONSTRAINT cognitive_manifest_pkey PRIMARY KEY (manifest_id);
ALTER TABLE ONLY cmis_knowledge.creative_templates     ADD CONSTRAINT creative_templates_pkey PRIMARY KEY (template_id);
ALTER TABLE ONLY cmis_knowledge.dev     ADD CONSTRAINT dev_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis_knowledge.direction_mappings     ADD CONSTRAINT direction_mappings_direction_name_key UNIQUE (direction_name);
ALTER TABLE ONLY cmis_knowledge.direction_mappings     ADD CONSTRAINT direction_mappings_pkey PRIMARY KEY (direction_id);
ALTER TABLE ONLY cmis_knowledge.embedding_api_config     ADD CONSTRAINT embedding_api_config_pkey PRIMARY KEY (config_id);
ALTER TABLE ONLY cmis_knowledge.embedding_api_logs     ADD CONSTRAINT embedding_api_logs_pkey PRIMARY KEY (log_id);
ALTER TABLE ONLY cmis_knowledge.embedding_update_queue     ADD CONSTRAINT embedding_update_queue_pkey PRIMARY KEY (queue_id);
ALTER TABLE ONLY cmis_knowledge.embeddings_cache     ADD CONSTRAINT embeddings_cache_pkey PRIMARY KEY (cache_id);
ALTER TABLE ONLY cmis_knowledge.embeddings_cache     ADD CONSTRAINT embeddings_cache_source_table_source_id_source_field_key UNIQUE (source_table, source_id, source_field);
ALTER TABLE ONLY cmis_knowledge.index_backup_2025_11_10     ADD CONSTRAINT index_backup_2025_11_10_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis_knowledge.index     ADD CONSTRAINT index_pkey PRIMARY KEY (knowledge_id);
ALTER TABLE ONLY cmis_knowledge.intent_mappings     ADD CONSTRAINT intent_mappings_intent_name_key UNIQUE (intent_name);
ALTER TABLE ONLY cmis_knowledge.intent_mappings     ADD CONSTRAINT intent_mappings_pkey PRIMARY KEY (intent_id);
ALTER TABLE ONLY cmis_knowledge.marketing     ADD CONSTRAINT marketing_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis_knowledge.org     ADD CONSTRAINT org_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis_knowledge.purpose_mappings     ADD CONSTRAINT purpose_mappings_pkey PRIMARY KEY (purpose_id);
ALTER TABLE ONLY cmis_knowledge.purpose_mappings     ADD CONSTRAINT purpose_mappings_purpose_name_key UNIQUE (purpose_name);
ALTER TABLE ONLY cmis_knowledge.research     ADD CONSTRAINT research_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis_knowledge.semantic_search_logs     ADD CONSTRAINT semantic_search_logs_pkey PRIMARY KEY (log_id);
ALTER TABLE ONLY cmis_knowledge.semantic_search_results_cache     ADD CONSTRAINT semantic_search_results_cache_pkey PRIMARY KEY (cache_id);
ALTER TABLE ONLY cmis_knowledge.temporal_analytics     ADD CONSTRAINT temporal_analytics_pkey PRIMARY KEY (delta_id);
ALTER TABLE ONLY cmis_marketing.assets     ADD CONSTRAINT assets_pkey PRIMARY KEY (asset_id);
ALTER TABLE ONLY cmis_marketing.generated_creatives     ADD CONSTRAINT generated_creatives_pkey PRIMARY KEY (creative_id);
ALTER TABLE ONLY cmis_marketing.video_scenarios     ADD CONSTRAINT video_scenarios_pkey PRIMARY KEY (scenario_id);
ALTER TABLE ONLY cmis_marketing.visual_concepts     ADD CONSTRAINT visual_concepts_pkey PRIMARY KEY (concept_id);
ALTER TABLE ONLY cmis_marketing.visual_scenarios     ADD CONSTRAINT visual_scenarios_pkey PRIMARY KEY (scenario_id);
ALTER TABLE ONLY cmis_marketing.voice_scripts     ADD CONSTRAINT voice_scripts_pkey PRIMARY KEY (script_id);
ALTER TABLE ONLY cmis_ops.schema_fixes_log     ADD CONSTRAINT schema_fixes_log_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis_staging.raw_channel_data     ADD CONSTRAINT raw_channel_data_pkey PRIMARY KEY (id);
ALTER TABLE ONLY cmis_system_health.cognitive_reports     ADD CONSTRAINT cognitive_reports_pkey PRIMARY KEY (report_id);
ALTER TABLE ONLY cmis_system_health.cognitive_vitality_log     ADD CONSTRAINT cognitive_vitality_log_pkey PRIMARY KEY (record_id);
ALTER TABLE ONLY lab.example_sets     ADD CONSTRAINT example_sets_pkey PRIMARY KEY (example_id);
ALTER TABLE ONLY lab.example_used_fields     ADD CONSTRAINT example_used_fields_pkey PRIMARY KEY (example_id, field_id);
ALTER TABLE ONLY lab.test_matrix     ADD CONSTRAINT test_matrix_pkey PRIMARY KEY (test_id);
ALTER TABLE ONLY operations.audit_log     ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);
ALTER TABLE ONLY operations.fix_tracking     ADD CONSTRAINT fix_tracking_pkey PRIMARY KEY (fix_id);
ALTER TABLE ONLY operations.migrations     ADD CONSTRAINT migrations_pkey PRIMARY KEY (migration_id);
ALTER TABLE ONLY public.awareness_stages     ADD CONSTRAINT awareness_stages_pkey PRIMARY KEY (stage);
ALTER TABLE ONLY public.cache     ADD CONSTRAINT cache_pkey PRIMARY KEY (key);
ALTER TABLE ONLY public.channel_formats     ADD CONSTRAINT channel_formats_channel_id_code_key UNIQUE (channel_id, code);
ALTER TABLE ONLY public.channel_formats     ADD CONSTRAINT channel_formats_pkey PRIMARY KEY (format_id);
ALTER TABLE ONLY public.channels     ADD CONSTRAINT channels_code_key UNIQUE (code);
ALTER TABLE ONLY public.channels     ADD CONSTRAINT channels_pkey PRIMARY KEY (channel_id);
ALTER TABLE ONLY public.cmis_access_control     ADD CONSTRAINT cmis_access_control_pkey PRIMARY KEY (rule_id);
ALTER TABLE ONLY public.cmis_system_health     ADD CONSTRAINT cmis_system_health_pkey PRIMARY KEY (check_id);
ALTER TABLE ONLY public.component_types     ADD CONSTRAINT component_types_pkey PRIMARY KEY (type_code);
ALTER TABLE ONLY public.frameworks     ADD CONSTRAINT frameworks_pkey PRIMARY KEY (framework_id);
ALTER TABLE ONLY public.funnel_stages     ADD CONSTRAINT funnel_stages_pkey PRIMARY KEY (stage);
ALTER TABLE ONLY public.industries     ADD CONSTRAINT industries_name_key UNIQUE (name);
ALTER TABLE ONLY public.industries     ADD CONSTRAINT industries_pkey PRIMARY KEY (industry_id);
ALTER TABLE ONLY public.jobs     ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.kpis     ADD CONSTRAINT kpis_pkey PRIMARY KEY (kpi);
ALTER TABLE ONLY public.marketing_objectives     ADD CONSTRAINT marketing_objectives_pkey PRIMARY KEY (objective);
ALTER TABLE ONLY public.markets     ADD CONSTRAINT markets_market_name_language_code_key UNIQUE (market_name, language_code);
ALTER TABLE ONLY public.markets     ADD CONSTRAINT markets_pkey PRIMARY KEY (market_id);
ALTER TABLE ONLY public.migration_log     ADD CONSTRAINT migration_log_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.modules_old     ADD CONSTRAINT modules_code_key UNIQUE (code);
ALTER TABLE ONLY public.modules_old     ADD CONSTRAINT modules_pkey PRIMARY KEY (module_id);
ALTER TABLE ONLY public.naming_templates_old     ADD CONSTRAINT naming_templates_pkey PRIMARY KEY (naming_id);
ALTER TABLE ONLY public.naming_templates_old     ADD CONSTRAINT naming_templates_scope_key UNIQUE (scope);
ALTER TABLE ONLY public.proof_layers     ADD CONSTRAINT proof_layers_pkey PRIMARY KEY (level);
ALTER TABLE ONLY public.sessions     ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.strategies     ADD CONSTRAINT strategies_pkey PRIMARY KEY (strategy);
ALTER TABLE ONLY public.tones     ADD CONSTRAINT tones_pkey PRIMARY KEY (tone);
ALTER TABLE ONLY public.view_definitions_backup     ADD CONSTRAINT view_definitions_backup_pkey PRIMARY KEY (viewname);
ALTER TABLE ONLY public.visual_kpis     ADD CONSTRAINT visual_kpis_name_key UNIQUE (name);
ALTER TABLE ONLY public.visual_kpis     ADD CONSTRAINT visual_kpis_pkey PRIMARY KEY (kpi_id);
ALTER TABLE ONLY public.visual_principles     ADD CONSTRAINT visual_principles_name_key UNIQUE (name);
ALTER TABLE ONLY public.visual_principles     ADD CONSTRAINT visual_principles_pkey PRIMARY KEY (principle_id);
ALTER TABLE ONLY public.visual_recommendations     ADD CONSTRAINT visual_recommendations_pkey PRIMARY KEY (recommendation_id);
ALTER TABLE ONLY cmis.ab_test_variations     ADD CONSTRAINT ab_test_variations_ab_test_id_fkey FOREIGN KEY (ab_test_id) REFERENCES cmis.ab_tests(ab_test_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.ab_tests     ADD CONSTRAINT ab_tests_ad_account_id_fkey FOREIGN KEY (ad_account_id) REFERENCES cmis.ad_accounts(id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.ad_accounts     ADD CONSTRAINT ad_accounts_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES cmis.integrations(integration_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.ad_accounts     ADD CONSTRAINT ad_accounts_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.ad_audiences     ADD CONSTRAINT ad_audiences_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES cmis.integrations(integration_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.ad_audiences     ADD CONSTRAINT ad_audiences_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.ad_campaigns     ADD CONSTRAINT ad_campaigns_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES cmis.integrations(integration_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.ad_campaigns     ADD CONSTRAINT ad_campaigns_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.ad_entities     ADD CONSTRAINT ad_entities_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES cmis.integrations(integration_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.ad_entities     ADD CONSTRAINT ad_entities_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.ad_metrics     ADD CONSTRAINT ad_metrics_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES cmis.integrations(integration_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.ad_metrics     ADD CONSTRAINT ad_metrics_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.ad_sets     ADD CONSTRAINT ad_sets_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES cmis.integrations(integration_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.ad_sets     ADD CONSTRAINT ad_sets_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.ai_actions     ADD CONSTRAINT ai_actions_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES cmis.audit_log(log_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.ai_generated_campaigns     ADD CONSTRAINT ai_generated_campaigns_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.anchors     ADD CONSTRAINT anchors_module_id_fkey FOREIGN KEY (module_id) REFERENCES cmis.modules(module_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.audio_templates     ADD CONSTRAINT audio_templates_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.audit_log     ADD CONSTRAINT audit_log_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.bundle_offerings     ADD CONSTRAINT bundle_offerings_bundle_id_fkey FOREIGN KEY (bundle_id) REFERENCES cmis.offerings_old(offering_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.bundle_offerings     ADD CONSTRAINT bundle_offerings_offering_id_fkey FOREIGN KEY (offering_id) REFERENCES cmis.offerings_old(offering_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.campaign_offerings     ADD CONSTRAINT campaign_offerings_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES cmis.campaigns(campaign_id) MATCH FULL ON DELETE CASCADE;
ALTER TABLE ONLY cmis.campaign_offerings     ADD CONSTRAINT campaign_offerings_offering_id_fkey FOREIGN KEY (offering_id) REFERENCES cmis.offerings_old(offering_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.campaign_performance_dashboard     ADD CONSTRAINT campaign_performance_dashboard_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES cmis.campaigns(campaign_id) MATCH FULL ON DELETE CASCADE;
ALTER TABLE ONLY cmis.ad_variants     ADD CONSTRAINT cmis_ad_variants_campaign_id_foreign FOREIGN KEY (campaign_id) REFERENCES cmis.ad_campaigns(id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.audience_templates     ADD CONSTRAINT cmis_audience_templates_org_id_foreign FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.inbox_items     ADD CONSTRAINT cmis_inbox_items_org_id_foreign FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.inbox_items     ADD CONSTRAINT cmis_inbox_items_social_account_id_foreign FOREIGN KEY (social_account_id) REFERENCES cmis.social_accounts(id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.post_approvals     ADD CONSTRAINT cmis_post_approvals_post_id_foreign FOREIGN KEY (post_id) REFERENCES cmis.social_posts(id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.publishing_queues     ADD CONSTRAINT cmis_publishing_queues_org_id_foreign FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.publishing_queues     ADD CONSTRAINT cmis_publishing_queues_social_account_id_foreign FOREIGN KEY (social_account_id) REFERENCES cmis.social_accounts(id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.scheduled_social_posts     ADD CONSTRAINT cmis_scheduled_social_posts_campaign_id_foreign FOREIGN KEY (campaign_id) REFERENCES cmis.campaigns(campaign_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.scheduled_social_posts     ADD CONSTRAINT cmis_scheduled_social_posts_org_id_foreign FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.cognitive_tracker_template     ADD CONSTRAINT cognitive_tracker_template_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.cognitive_trends     ADD CONSTRAINT cognitive_trends_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.compliance_audits     ADD CONSTRAINT compliance_audits_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES cmis.compliance_rules(rule_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.compliance_rule_channels     ADD CONSTRAINT compliance_rule_channels_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES cmis.compliance_rules(rule_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.content_items     ADD CONSTRAINT content_items_context_id_fkey FOREIGN KEY (context_id) REFERENCES cmis.value_contexts(context_id);
ALTER TABLE ONLY cmis.content_items     ADD CONSTRAINT content_items_creative_context_id_fkey FOREIGN KEY (creative_context_id) REFERENCES cmis.creative_contexts(context_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.content_items     ADD CONSTRAINT content_items_example_id_fkey FOREIGN KEY (example_id) REFERENCES lab.example_sets(example_id);
ALTER TABLE ONLY cmis.content_items     ADD CONSTRAINT content_items_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES cmis.content_plans(plan_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.content_plans     ADD CONSTRAINT content_plans_brief_id_fkey FOREIGN KEY (brief_id) REFERENCES cmis.creative_briefs(brief_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.content_plans     ADD CONSTRAINT content_plans_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES cmis.campaigns(campaign_id) MATCH FULL ON DELETE SET NULL;
ALTER TABLE ONLY cmis.content_plans     ADD CONSTRAINT content_plans_creative_context_id_fkey FOREIGN KEY (creative_context_id) REFERENCES cmis.creative_contexts(context_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.content_plans     ADD CONSTRAINT content_plans_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.contexts_base     ADD CONSTRAINT contexts_base_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id);
ALTER TABLE ONLY cmis.contexts     ADD CONSTRAINT contexts_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES cmis.campaigns(campaign_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.contexts_creative     ADD CONSTRAINT contexts_creative_context_id_fkey FOREIGN KEY (context_id) REFERENCES cmis.contexts_base(id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.contexts_offering     ADD CONSTRAINT contexts_offering_context_id_fkey FOREIGN KEY (context_id) REFERENCES cmis.contexts_base(id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.contexts_value     ADD CONSTRAINT contexts_value_context_id_fkey FOREIGN KEY (context_id) REFERENCES cmis.contexts_base(id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.copy_components     ADD CONSTRAINT copy_components_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES cmis.campaigns(campaign_id) MATCH FULL ON DELETE SET NULL;
ALTER TABLE ONLY cmis.copy_components     ADD CONSTRAINT copy_components_context_id_fkey FOREIGN KEY (context_id) REFERENCES cmis.value_contexts(context_id);
ALTER TABLE ONLY cmis.copy_components     ADD CONSTRAINT copy_components_example_id_fkey FOREIGN KEY (example_id) REFERENCES lab.example_sets(example_id);
ALTER TABLE ONLY cmis.copy_components     ADD CONSTRAINT copy_components_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES cmis.content_plans(plan_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.creative_assets     ADD CONSTRAINT creative_assets_brief_id_fkey FOREIGN KEY (brief_id) REFERENCES cmis.creative_briefs(brief_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.creative_assets     ADD CONSTRAINT creative_assets_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES cmis.campaigns(campaign_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY cmis.creative_assets     ADD CONSTRAINT creative_assets_context_id_fkey FOREIGN KEY (context_id) REFERENCES cmis.value_contexts(context_id);
ALTER TABLE ONLY cmis.creative_assets     ADD CONSTRAINT creative_assets_creative_context_id_fkey FOREIGN KEY (creative_context_id) REFERENCES cmis.creative_contexts(context_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.creative_assets     ADD CONSTRAINT creative_assets_example_id_fkey FOREIGN KEY (example_id) REFERENCES lab.example_sets(example_id);
ALTER TABLE ONLY cmis.creative_assets     ADD CONSTRAINT creative_assets_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.creative_briefs     ADD CONSTRAINT creative_briefs_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.creative_contexts     ADD CONSTRAINT creative_contexts_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.creative_outputs     ADD CONSTRAINT creative_outputs_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES cmis.campaigns(campaign_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.creative_outputs     ADD CONSTRAINT creative_outputs_context_id_fkey FOREIGN KEY (context_id) REFERENCES cmis.contexts(context_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.data_feeds     ADD CONSTRAINT data_feeds_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.dataset_files     ADD CONSTRAINT dataset_files_pkg_id_fkey FOREIGN KEY (pkg_id) REFERENCES cmis.dataset_packages(pkg_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.experiment_variants     ADD CONSTRAINT experiment_variants_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES cmis.creative_assets(asset_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.experiment_variants     ADD CONSTRAINT experiment_variants_exp_id_fkey FOREIGN KEY (exp_id) REFERENCES cmis.experiments(exp_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.experiments     ADD CONSTRAINT experiments_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES cmis.campaigns(campaign_id) MATCH FULL ON DELETE SET NULL;
ALTER TABLE ONLY cmis.experiments     ADD CONSTRAINT experiments_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.export_bundle_items     ADD CONSTRAINT export_bundle_items_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES cmis.creative_assets(asset_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.export_bundle_items     ADD CONSTRAINT export_bundle_items_bundle_id_fkey FOREIGN KEY (bundle_id) REFERENCES cmis.export_bundles(bundle_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.export_bundles     ADD CONSTRAINT export_bundles_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.feed_items     ADD CONSTRAINT feed_items_feed_id_fkey FOREIGN KEY (feed_id) REFERENCES cmis.data_feeds(feed_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.field_aliases     ADD CONSTRAINT field_aliases_field_id_fkey FOREIGN KEY (field_id) REFERENCES cmis.field_definitions(field_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.field_definitions     ADD CONSTRAINT field_definitions_guidance_anchor_fkey FOREIGN KEY (guidance_anchor) REFERENCES cmis.anchors(anchor_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.field_definitions     ADD CONSTRAINT field_definitions_module_id_fkey FOREIGN KEY (module_id) REFERENCES cmis.modules(module_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.field_values     ADD CONSTRAINT field_values_context_id_fkey FOREIGN KEY (context_id) REFERENCES cmis.value_contexts(context_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.field_values     ADD CONSTRAINT field_values_field_id_fkey FOREIGN KEY (field_id) REFERENCES cmis.field_definitions(field_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.campaigns     ADD CONSTRAINT fk_campaigns_context FOREIGN KEY (context_id) REFERENCES cmis.value_contexts(context_id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE ONLY cmis.content_items     ADD CONSTRAINT fk_content_item_asset FOREIGN KEY (asset_id) REFERENCES cmis.creative_assets(asset_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.content_items     ADD CONSTRAINT fk_content_items_context FOREIGN KEY (context_id) REFERENCES cmis.creative_contexts(context_id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE ONLY cmis.content_items     ADD CONSTRAINT fk_content_items_creative_context FOREIGN KEY (creative_context_id) REFERENCES cmis.creative_contexts(context_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.content_items     ADD CONSTRAINT fk_content_items_org_id FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.content_plans     ADD CONSTRAINT fk_content_plans_org_id FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.creative_outputs     ADD CONSTRAINT fk_creative_outputs_context FOREIGN KEY (context_id) REFERENCES cmis.creative_contexts(context_id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE ONLY cmis.user_orgs     ADD CONSTRAINT fk_user_orgs_role FOREIGN KEY (role_id) REFERENCES cmis.roles(role_id);
ALTER TABLE ONLY cmis.flow_steps     ADD CONSTRAINT flow_steps_flow_id_fkey FOREIGN KEY (flow_id) REFERENCES cmis.flows(flow_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.flows     ADD CONSTRAINT flows_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.offerings_full_details     ADD CONSTRAINT offerings_full_details_offering_id_fkey FOREIGN KEY (offering_id) REFERENCES cmis.offerings_old(offering_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.offerings_old     ADD CONSTRAINT offerings_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.org_datasets     ADD CONSTRAINT org_datasets_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.org_datasets     ADD CONSTRAINT org_datasets_pkg_id_fkey FOREIGN KEY (pkg_id) REFERENCES cmis.dataset_packages(pkg_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.org_markets     ADD CONSTRAINT org_markets_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.performance_metrics     ADD CONSTRAINT performance_metrics_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES cmis.campaigns(campaign_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.performance_metrics     ADD CONSTRAINT performance_metrics_output_id_fkey FOREIGN KEY (output_id) REFERENCES cmis.creative_outputs(output_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.predictive_visual_engine     ADD CONSTRAINT predictive_visual_engine_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.prompt_template_contracts     ADD CONSTRAINT prompt_template_contracts_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES cmis.output_contracts(contract_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.prompt_template_contracts     ADD CONSTRAINT prompt_template_contracts_prompt_id_fkey FOREIGN KEY (prompt_id) REFERENCES cmis.prompt_templates(prompt_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.prompt_template_presql     ADD CONSTRAINT prompt_template_presql_prompt_id_fkey FOREIGN KEY (prompt_id) REFERENCES cmis.prompt_templates(prompt_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.prompt_template_presql     ADD CONSTRAINT prompt_template_presql_snippet_id_fkey FOREIGN KEY (snippet_id) REFERENCES cmis.sql_snippets(snippet_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.prompt_template_required_fields     ADD CONSTRAINT prompt_template_required_fields_field_id_fkey FOREIGN KEY (field_id) REFERENCES cmis.field_definitions(field_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.prompt_template_required_fields     ADD CONSTRAINT prompt_template_required_fields_prompt_id_fkey FOREIGN KEY (prompt_id) REFERENCES cmis.prompt_templates(prompt_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.prompt_templates     ADD CONSTRAINT prompt_templates_module_id_fkey FOREIGN KEY (module_id) REFERENCES cmis.modules(module_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.role_permissions     ADD CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES cmis.permissions(permission_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.role_permissions     ADD CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES cmis.roles(role_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.roles     ADD CONSTRAINT roles_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.scene_library     ADD CONSTRAINT scene_library_anchor_fkey FOREIGN KEY (anchor) REFERENCES cmis.anchors(anchor_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.scene_library     ADD CONSTRAINT scene_library_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.segments     ADD CONSTRAINT segments_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.session_context     ADD CONSTRAINT session_context_active_org_id_fkey FOREIGN KEY (active_org_id) REFERENCES cmis.orgs(org_id);
ALTER TABLE ONLY cmis.session_context     ADD CONSTRAINT session_context_session_id_fkey FOREIGN KEY (session_id) REFERENCES cmis.user_sessions(session_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.social_account_metrics     ADD CONSTRAINT social_account_metrics_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES cmis.integrations(integration_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.social_accounts     ADD CONSTRAINT social_accounts_account_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES cmis.integrations(integration_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.social_accounts     ADD CONSTRAINT social_accounts_account_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.social_posts     ADD CONSTRAINT social_posts_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES cmis.integrations(integration_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.social_posts     ADD CONSTRAINT social_posts_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.sync_logs     ADD CONSTRAINT sync_logs_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES cmis.integrations(integration_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.sync_logs     ADD CONSTRAINT sync_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.team_account_access     ADD CONSTRAINT team_account_access_social_account_id_fkey FOREIGN KEY (social_account_id) REFERENCES cmis.social_accounts(id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.team_invitations     ADD CONSTRAINT team_invitations_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.team_invitations     ADD CONSTRAINT team_invitations_role_id_fkey FOREIGN KEY (role_id) REFERENCES cmis.roles(role_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.user_activities     ADD CONSTRAINT user_activities_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id);
ALTER TABLE ONLY cmis.user_activities     ADD CONSTRAINT user_activities_session_id_fkey FOREIGN KEY (session_id) REFERENCES cmis.user_sessions(session_id);
ALTER TABLE ONLY cmis.user_orgs     ADD CONSTRAINT user_orgs_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.user_orgs     ADD CONSTRAINT user_orgs_user_id_fkey FOREIGN KEY (user_id) REFERENCES cmis.users(user_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.user_permissions     ADD CONSTRAINT user_permissions_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.user_permissions     ADD CONSTRAINT user_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES cmis.permissions(permission_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.value_contexts     ADD CONSTRAINT value_contexts_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES cmis.campaigns(campaign_id) MATCH FULL ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY cmis.value_contexts     ADD CONSTRAINT value_contexts_offering_id_fkey FOREIGN KEY (offering_id) REFERENCES cmis.offerings_old(offering_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.value_contexts     ADD CONSTRAINT value_contexts_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.value_contexts     ADD CONSTRAINT value_contexts_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES cmis.segments(segment_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.variation_policies     ADD CONSTRAINT variation_policies_naming_ref_fkey FOREIGN KEY (naming_ref) REFERENCES cmis.naming_templates(naming_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.variation_policies     ADD CONSTRAINT variation_policies_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis.video_scenes     ADD CONSTRAINT video_scenes_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES cmis.creative_assets(asset_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis.video_templates     ADD CONSTRAINT video_templates_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE SET NULL;
ALTER TABLE ONLY cmis_dev.dev_logs     ADD CONSTRAINT dev_logs_task_id_fkey FOREIGN KEY (task_id) REFERENCES cmis_dev.dev_tasks(task_id);
ALTER TABLE ONLY cmis_knowledge.dev     ADD CONSTRAINT dev_knowledge_id_fkey FOREIGN KEY (knowledge_id) REFERENCES cmis_knowledge.index(knowledge_id);
ALTER TABLE ONLY cmis_knowledge.dev     ADD CONSTRAINT dev_parent_knowledge_id_fkey FOREIGN KEY (parent_knowledge_id) REFERENCES cmis_knowledge.index(knowledge_id);
ALTER TABLE ONLY cmis_knowledge.direction_mappings     ADD CONSTRAINT direction_mappings_parent_direction_id_fkey FOREIGN KEY (parent_direction_id) REFERENCES cmis_knowledge.direction_mappings(direction_id);
ALTER TABLE ONLY cmis_knowledge.intent_mappings     ADD CONSTRAINT intent_mappings_parent_intent_id_fkey FOREIGN KEY (parent_intent_id) REFERENCES cmis_knowledge.intent_mappings(intent_id);
ALTER TABLE ONLY cmis_knowledge.marketing     ADD CONSTRAINT marketing_knowledge_id_fkey FOREIGN KEY (knowledge_id) REFERENCES cmis_knowledge.index(knowledge_id);
ALTER TABLE ONLY cmis_knowledge.org     ADD CONSTRAINT org_knowledge_id_fkey FOREIGN KEY (knowledge_id) REFERENCES cmis_knowledge.index(knowledge_id);
ALTER TABLE ONLY cmis_knowledge.research     ADD CONSTRAINT research_knowledge_id_fkey FOREIGN KEY (knowledge_id) REFERENCES cmis_knowledge.index(knowledge_id);
ALTER TABLE ONLY cmis_knowledge.temporal_analytics     ADD CONSTRAINT temporal_analytics_knowledge_id_fkey FOREIGN KEY (knowledge_id) REFERENCES cmis_knowledge.index(knowledge_id);
ALTER TABLE ONLY cmis_marketing.assets     ADD CONSTRAINT assets_task_id_fkey FOREIGN KEY (task_id) REFERENCES cmis_dev.dev_tasks(task_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis_marketing.video_scenarios     ADD CONSTRAINT video_scenarios_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES cmis_marketing.assets(asset_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis_marketing.video_scenarios     ADD CONSTRAINT video_scenarios_task_id_fkey FOREIGN KEY (task_id) REFERENCES cmis_dev.dev_tasks(task_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis_marketing.visual_concepts     ADD CONSTRAINT visual_concepts_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES cmis_marketing.assets(asset_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis_marketing.visual_scenarios     ADD CONSTRAINT visual_scenarios_creative_id_fkey FOREIGN KEY (creative_id) REFERENCES cmis_marketing.generated_creatives(creative_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis_marketing.voice_scripts     ADD CONSTRAINT voice_scripts_scenario_id_fkey FOREIGN KEY (scenario_id) REFERENCES cmis_marketing.video_scenarios(scenario_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis_marketing.voice_scripts     ADD CONSTRAINT voice_scripts_task_id_fkey FOREIGN KEY (task_id) REFERENCES cmis_dev.dev_tasks(task_id) ON DELETE CASCADE;
ALTER TABLE ONLY cmis_staging.raw_channel_data     ADD CONSTRAINT raw_channel_data_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES cmis.integrations(integration_id);
ALTER TABLE ONLY lab.example_sets     ADD CONSTRAINT example_sets_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES cmis.campaigns(campaign_id) MATCH FULL ON DELETE SET NULL;
ALTER TABLE ONLY lab.example_used_fields     ADD CONSTRAINT example_used_fields_example_id_fkey FOREIGN KEY (example_id) REFERENCES lab.example_sets(example_id) ON DELETE CASCADE;
ALTER TABLE ONLY lab.example_used_fields     ADD CONSTRAINT example_used_fields_field_id_fkey FOREIGN KEY (field_id) REFERENCES cmis.field_definitions(field_id) ON DELETE CASCADE;
ALTER TABLE ONLY lab.test_matrix     ADD CONSTRAINT test_matrix_org_id_fkey FOREIGN KEY (org_id) REFERENCES cmis.orgs(org_id) ON DELETE SET NULL;
ALTER TABLE ONLY public.channel_formats     ADD CONSTRAINT channel_formats_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.channels(channel_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.visual_recommendations     ADD CONSTRAINT visual_recommendations_linked_kpi_fkey FOREIGN KEY (linked_kpi) REFERENCES public.visual_kpis(name);
ALTER TABLE ONLY public.visual_recommendations     ADD CONSTRAINT visual_recommendations_objective_code_fkey FOREIGN KEY (objective_code) REFERENCES public.marketing_objectives(objective);
ALTER TABLE ONLY public.visual_recommendations     ADD CONSTRAINT visual_recommendations_recommended_principle_fkey FOREIGN KEY (recommended_principle) REFERENCES public.visual_principles(name);
