COMMENT ON EXTENSION plpython3u IS 'PL/Python3U untrusted procedural language';
COMMENT ON EXTENSION btree_gin IS 'support for indexing common datatypes in GIN';
COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';
COMMENT ON EXTENSION ltree IS 'data type for hierarchical tree-like structures';
COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';
COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';
COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';
COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';
COMMENT ON FUNCTION cmis.check_permission(p_user_id uuid, p_org_id uuid, p_permission_code text) IS 'التحقق من صلاحيات المستخدم مع دعم cache و soft delete - محدثة';
COMMENT ON FUNCTION cmis.check_permission_tx(p_permission text) IS 'التحقق من صلاحية باستخدام السياق المحلي للمعاملة - أسهل للاستخدام من API';
COMMENT ON FUNCTION cmis.get_current_org_id_tx() IS 'الحصول على org_id من السياق المحلي للمعاملة';
COMMENT ON FUNCTION cmis.get_current_user_id_tx() IS 'الحصول على user_id من السياق المحلي للمعاملة';
COMMENT ON FUNCTION cmis.init_transaction_context(p_user_id uuid, p_org_id uuid) IS 'تهيئة سياق الأمان للمعاملة الحالية باستخدام SET LOCAL - v2.0';
COMMENT ON FUNCTION cmis.test_new_security_context() IS 'اختبار شامل للنظام الأمني الجديد';
COMMENT ON FUNCTION cmis.validate_transaction_context() IS 'التحقق من صحة سياق المعاملة وإرجاع معلومات المستخدم والمؤسسة';
COMMENT ON FUNCTION cmis.verify_rbac_policies() IS 'التحقق من حالة سياسات الأمان وما إذا كانت تستخدم الدالة المحسنة';
COMMENT ON FUNCTION cmis_ops.update_timestamp() IS 'دالة قياسية لتحديث عمود updated_at تلقائيًا قبل تنفيذ أي UPDATE على الصف.';
COMMENT ON TABLE cmis.ab_test_variations IS 'Variations within an A/B test - Sprint 4.6';
COMMENT ON TABLE cmis.ab_tests IS 'A/B testing experiments for ad campaigns - Sprint 4.6';
COMMENT ON TABLE cmis.ad_variants IS 'A/B testing variants for ad campaigns (max 3 variants)';
COMMENT ON COLUMN cmis.ad_variants.variant_type IS 'creative, copy, or audience';
COMMENT ON COLUMN cmis.ad_variants.budget_allocation IS 'Percentage of campaign budget (0-100)';
COMMENT ON TABLE cmis.audience_templates IS 'Reusable audience targeting templates for multi-platform campaigns';
COMMENT ON COLUMN cmis.audience_templates.targeting_criteria IS 'Platform-agnostic targeting configuration';
COMMENT ON TABLE cmis.campaign_context_links IS 'Links campaigns to their various contexts with flexible relationship types';
COMMENT ON COLUMN cmis.campaign_context_links.link_type IS 'Type of link: primary, secondary, reference, or historical';
COMMENT ON COLUMN cmis.campaign_context_links.link_strength IS 'Strength of the relationship (0.0 to 1.0)';
COMMENT ON TABLE cmis.campaigns IS 'المرجع الموحّد لجميع الحملات. استخدم هذا الجدول بدل أي نسخة قديمة.';
COMMENT ON TABLE cmis.copy_components IS 'مكونات المحتوى النصي المُولَّدة مثل hook و headline و CTA. كل مكون يمثل قطعة نصية قابلة لإعادة الاستخدام ضمن السياق الإبداعي.';
COMMENT ON COLUMN cmis.copy_components.type_code IS 'نوع المكون النصي: hook, headline, benefit, proof... تُستخدم لتحديد وظيفة النص داخل الرسالة الإعلانية.';
COMMENT ON COLUMN cmis.copy_components.context_id IS 'السياق المعرفي الذي يربط هذا المكون بحملة معينة، جمهور، نبرة، أو مرحلة وعي معينة.';
COMMENT ON COLUMN cmis.copy_components.example_id IS 'معرّف مجموعة الحقول (example_set) التي تم استخدامها لتوليد هذا النص. يساعد في تتبع وفهم المنطق التوليدي.';
COMMENT ON TABLE cmis.inbox_items IS 'Unified inbox for comments, messages, and mentions from all platforms';
COMMENT ON COLUMN cmis.inbox_items.item_type IS 'comment, message, or mention';
COMMENT ON COLUMN cmis.inbox_items.status IS 'unread, replied, or archived';
COMMENT ON COLUMN cmis.performance_metrics.observed_at IS 'زمن الرصد (كان ts في النسخة القديمة).';
COMMENT ON TABLE cmis.post_approvals IS 'Post approval workflow system';
COMMENT ON COLUMN cmis.post_approvals.status IS 'pending, approved, or rejected';
COMMENT ON TABLE cmis.publishing_queues IS 'Buffer-style publishing queues with custom time slots per social account';
COMMENT ON TABLE cmis.scheduled_reports IS 'Scheduled report configurations for automated PDF/CSV generation';
COMMENT ON COLUMN cmis.scheduled_reports.report_type IS 'Type of report: performance, ai_insights, organization_overview, content_analysis';
COMMENT ON COLUMN cmis.scheduled_reports.frequency IS 'Report frequency: daily, weekly, monthly';
COMMENT ON COLUMN cmis.scheduled_reports.delivery_method IS 'Delivery method: email, storage, both';
COMMENT ON COLUMN cmis.scheduled_social_posts.deleted_at IS 'تاريخ الحذف الناعم - NULL يعني أن المنشور نشط';
COMMENT ON TABLE cmis.security_context_audit IS 'سجل تدقيق لجميع عمليات تهيئة سياق الأمان';
COMMENT ON VIEW cmis.v_deleted_records IS 'عرض جميع السجلات المحذوفة - للمديرين فقط';
COMMENT ON VIEW cmis.v_security_context_summary IS 'ملخص نشاط سياقات الأمان خلال آخر 24 ساعة';
COMMENT ON COLUMN cmis_knowledge.dev.tier IS 'تصنيف جودة المعرفة (1=حرجة، 2=قياسية، 3=ثانوية)';
COMMENT ON COLUMN cmis_knowledge.index.tier IS 'تصنيف جودة المعرفة (1=حرجة، 2=قياسية، 3=ثانوية)';
COMMENT ON COLUMN cmis_knowledge.marketing.tier IS 'تصنيف جودة المعرفة (1=حرجة، 2=قياسية، 3=ثانوية)';
COMMENT ON COLUMN cmis_knowledge.org.tier IS 'تصنيف جودة المعرفة (1=حرجة، 2=قياسية، 3=ثانوية)';
COMMENT ON COLUMN cmis_knowledge.research.tier IS 'تصنيف جودة المعرفة (1=حرجة، 2=قياسية، 3=ثانوية)';
COMMENT ON CONSTRAINT fk_content_items_creative_context ON cmis.content_items IS 'Links content items to their creative context (optional)';
COMMENT ON CONSTRAINT fk_content_items_org_id ON cmis.content_items IS 'Ensures content items belong to valid organizations';
COMMENT ON CONSTRAINT fk_content_plans_org_id ON cmis.content_plans IS 'Ensures content plans belong to valid organizations';
