CREATE TABLE archive.backup_integrations_cmis (
    integration_id uuid,
    org_id uuid,
    platform text,
    account_id text,
    access_token text,
    is_active boolean,
    created_at timestamp with time zone,
    id bigint NOT NULL
);
CREATE TABLE archive.contexts_unified_backup (
    id uuid,
    context_type character varying(50),
    name character varying(255),
    description text,
    status character varying(50),
    creative_brief text,
    brand_guidelines jsonb,
    visual_style jsonb,
    tone_of_voice text,
    target_platforms text[],
    creative_assets jsonb,
    value_proposition text,
    target_audience jsonb,
    key_messages text[],
    pain_points text[],
    benefits text[],
    differentiators text[],
    offering_details jsonb,
    pricing_info jsonb,
    availability jsonb,
    features text[],
    specifications jsonb,
    terms_conditions text,
    parent_context_id uuid,
    related_contexts uuid[],
    org_id uuid,
    created_by uuid,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone,
    version integer,
    metadata jsonb,
    tags text[],
    categories text[],
    keywords text[],
    search_vector tsvector
);
CREATE TABLE archive.embedding_update_queue_backup (
    queue_id uuid,
    knowledge_id uuid,
    source_table text,
    source_field text,
    priority integer,
    status text,
    retry_count integer,
    max_retries integer,
    error_message text,
    created_at timestamp with time zone,
    processing_started_at timestamp with time zone,
    processed_at timestamp with time zone,
    id bigint NOT NULL
);
