<?php

return [
    // Report Titles
    'analytics_report' => 'Analytics Report',
    'comprehensive_performance_analysis' => 'Comprehensive Performance Analysis',

    // Meta Information
    'report_period' => 'Report Period',
    'platform_filter' => 'Platform Filter',
    'generated_at' => 'Generated At',
    'all_platforms' => 'All Platforms',
    'days' => 'Days',

    // Sections
    'overview' => 'Overview',
    'posts_by_platform' => 'Posts by Platform',
    'campaign_performance' => 'Campaign Performance',
    'top_performing_posts' => 'Top Performing Posts',
    'daily_trends' => 'Daily Trends',

    // Overview Metrics
    'total_posts' => 'Total Posts',
    'total_comments' => 'Total Comments',
    'total_messages' => 'Total Messages',
    'active_campaigns' => 'Active Campaigns',

    // Table Headers
    'platform' => 'Platform',
    'post_count' => 'Post Count',
    'percentage' => 'Percentage',
    'campaign_name' => 'Campaign Name',
    'status' => 'Status',
    'impressions' => 'Impressions',
    'clicks' => 'Clicks',
    'ctr' => 'CTR',
    'spend' => 'Spend',
    'content' => 'Content',
    'likes' => 'Likes',
    'comments' => 'Comments',
    'shares' => 'Shares',
    'engagement' => 'Engagement',
    'date' => 'Date',
    'posts' => 'Posts',

    // Footer
    'generated_by_cmis' => 'Generated by CMIS - Cognitive Marketing Intelligence Suite',
    'confidential_report' => 'This is a confidential report. Unauthorized distribution is prohibited.',

    // Export Messages
    'export_started' => 'Export started...',
    'export_complete' => 'Export completed successfully',
    'export_failed' => 'Export failed. Please try again.',
    'preparing_pdf' => 'Preparing PDF export...',
    'preparing_excel' => 'Preparing Excel export...',
    'downloading' => 'Downloading...',
];
