<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Domain: All Database Tables
 *
 * Description: Creates all 189 tables from database/schema.sql
 *
 * AI Agent Context: This creates the complete table structure.
 * All tables are created without constraints/indexes for dependency-free creation.
 */
return new class extends Migration
{
    /**
     * Disable wrapping this migration in a transaction.
     * Extensions and large SQL imports work better without transactions.
     */
    public $withinTransaction = false;

    public function up(): void
    {
        // Drop and recreate extensions in the public schema
        // This ensures the vector type is in public schema where SQL file expects it
        // Using CASCADE to drop dependent objects, then recreate
        DB::unprepared('DROP EXTENSION IF EXISTS vector CASCADE');
        DB::unprepared('DROP EXTENSION IF EXISTS ltree CASCADE');
        DB::unprepared('DROP EXTENSION IF EXISTS citext CASCADE');
        DB::unprepared('DROP EXTENSION IF EXISTS btree_gin CASCADE');
        DB::unprepared('DROP EXTENSION IF EXISTS pg_trgm CASCADE');
        DB::unprepared('DROP EXTENSION IF EXISTS pgcrypto CASCADE');
        DB::unprepared('DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE');

        // Now create them in public schema
        DB::unprepared('CREATE EXTENSION "uuid-ossp" WITH SCHEMA public');
        DB::unprepared('CREATE EXTENSION pgcrypto WITH SCHEMA public');
        DB::unprepared('CREATE EXTENSION pg_trgm WITH SCHEMA public');
        DB::unprepared('CREATE EXTENSION btree_gin WITH SCHEMA public');
        DB::unprepared('CREATE EXTENSION citext WITH SCHEMA public');
        DB::unprepared('CREATE EXTENSION ltree WITH SCHEMA public');
        DB::unprepared('CREATE EXTENSION vector WITH SCHEMA public');

        // Drop all existing tables in schemas to ensure clean state
        // Exclude 'migrations' table as Laravel manages it
        $schemas = ['public', 'cmis', 'cmis_ai_analytics', 'cmis_analytics', 'cmis_audit', 'cmis_dev',
                    'cmis_knowledge', 'cmis_marketing', 'cmis_ops', 'cmis_security_backup_20251111_202413',
                    'cmis_staging', 'cmis_system_health', 'archive', 'lab', 'operations'];

        foreach ($schemas as $schema) {
            // Drop all tables in schema except migrations (Laravel managed)
            DB::unprepared("
                DO $$
                DECLARE
                    r RECORD;
                BEGIN
                    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = '{$schema}' AND tablename != 'migrations') LOOP
                        EXECUTE 'DROP TABLE IF EXISTS {$schema}.' || quote_ident(r.tablename) || ' CASCADE';
                    END LOOP;
                END $$;
            ");
        }

        $sql = file_get_contents(database_path('sql/complete_tables.sql'));

        if (!empty(trim($sql))) {
            // Replace CREATE TABLE migrations statements to use CREATE TABLE IF NOT EXISTS
            // This prevents conflicts with Laravel's migrations table
            $sql = preg_replace(
                '/CREATE TABLE ([\w.]+\.)?migrations \(/i',
                'CREATE TABLE IF NOT EXISTS $1migrations (',
                $sql
            );

            try {
                DB::unprepared($sql);
            } catch (\Exception $e) {
                // Log the error for debugging, but check if it's a critical error
                \Log::error('Error creating tables from complete_tables.sql: ' . $e->getMessage());

                // Re-throw the exception - let Laravel handle migration failures properly
                // PostgreSQL transactions are aborted after an error, so we can't query
                // the database state to check if tables exist within the same transaction
                throw $e;
            }
        }

        // Ensure Laravel's migrations table supports identity inserts when using the
        // cmis schema search path. The raw schema dump creates cmis.migrations with
        // a plain integer primary key which lacks a default sequence, so subsequent
        // inserts from Laravel will fail with a NOT NULL violation. We explicitly
        // attach an identity to keep the table compatible with Laravel's migration
        // repository expectations.
        $identity = DB::selectOne(<<<SQL
            SELECT identity_generation
            FROM information_schema.columns
            WHERE table_schema = 'cmis'
              AND table_name = 'migrations'
              AND column_name = 'id'
        SQL);

        if (!$identity || !in_array($identity->identity_generation, ['ALWAYS', 'BY DEFAULT'], true)) {
            try {
                DB::statement('ALTER TABLE cmis.migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
            } catch (\Exception $e) {
                // Identity may already exist from a previous migration or manual setup
                // This is safe to ignore as long as the identity_generation is set
                if (!str_contains($e->getMessage(), 'already has a default')) {
                    throw $e;
                }
            }
        }
    }

    public function down(): void
    {
        // Tables will be dropped when schemas are dropped
    }
};
