<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Domain: All Database Tables
 *
 * Description: Creates all 189 tables from database/schema.sql
 *
 * AI Agent Context: This creates the complete table structure.
 * All tables are created without constraints/indexes for dependency-free creation.
 */
return new class extends Migration
{
    public function up(): void
    {
        // Drop all existing tables in schemas to ensure clean state
        // Exclude 'migrations' table as Laravel manages it
        $schemas = ['public', 'cmis', 'cmis_ai_analytics', 'cmis_analytics', 'cmis_audit', 'cmis_dev',
                    'cmis_knowledge', 'cmis_marketing', 'cmis_ops', 'cmis_security_backup_20251111_202413',
                    'cmis_staging', 'cmis_system_health', 'archive', 'lab', 'operations'];

        foreach ($schemas as $schema) {
            // Drop all tables in schema except migrations (Laravel managed)
            DB::unprepared("
                DO $$
                DECLARE
                    r RECORD;
                BEGIN
                    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = '{$schema}' AND tablename != 'migrations') LOOP
                        EXECUTE 'DROP TABLE IF EXISTS {$schema}.' || quote_ident(r.tablename) || ' CASCADE';
                    END LOOP;
                END $$;
            ");
        }

        $sql = file_get_contents(database_path('sql/complete_tables.sql'));

        if (!empty(trim($sql))) {
            // Replace CREATE TABLE migrations statements to use CREATE TABLE IF NOT EXISTS
            // This prevents conflicts with Laravel's migrations table
            $sql = preg_replace(
                '/CREATE TABLE ([\w.]+\.)?migrations \(/i',
                'CREATE TABLE IF NOT EXISTS $1migrations (',
                $sql
            );

            DB::unprepared($sql);
        }

        // Ensure Laravel's migrations table supports identity inserts when using the
        // cmis schema search path. The raw schema dump creates cmis.migrations with
        // a plain integer primary key which lacks a default sequence, so subsequent
        // inserts from Laravel will fail with a NOT NULL violation. We explicitly
        // attach an identity to keep the table compatible with Laravel's migration
        // repository expectations.
        $identity = DB::selectOne(<<<SQL
            SELECT identity_generation
            FROM information_schema.columns
            WHERE table_schema = 'cmis'
              AND table_name = 'migrations'
              AND column_name = 'id'
        SQL);

        if (!$identity || $identity->identity_generation === null) {
            DB::statement('ALTER TABLE cmis.migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
        }
    }

    public function down(): void
    {
        // Tables will be dropped when schemas are dropped
    }
};
