<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Insert categories
        $categories = [
            [
                'category_id' => Str::uuid()->toString(),
                'slug' => 'core',
                'name_key' => 'marketplace.categories.core',
                'description_key' => 'marketplace.categories.core_description',
                'icon' => 'fa-home',
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'category_id' => Str::uuid()->toString(),
                'slug' => 'marketing',
                'name_key' => 'marketplace.categories.marketing',
                'description_key' => 'marketplace.categories.marketing_description',
                'icon' => 'fa-bullhorn',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'category_id' => Str::uuid()->toString(),
                'slug' => 'analytics',
                'name_key' => 'marketplace.categories.analytics',
                'description_key' => 'marketplace.categories.analytics_description',
                'icon' => 'fa-chart-line',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'category_id' => Str::uuid()->toString(),
                'slug' => 'ai',
                'name_key' => 'marketplace.categories.ai',
                'description_key' => 'marketplace.categories.ai_description',
                'icon' => 'fa-robot',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'category_id' => Str::uuid()->toString(),
                'slug' => 'automation',
                'name_key' => 'marketplace.categories.automation',
                'description_key' => 'marketplace.categories.automation_description',
                'icon' => 'fa-cogs',
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'category_id' => Str::uuid()->toString(),
                'slug' => 'system',
                'name_key' => 'marketplace.categories.system',
                'description_key' => 'marketplace.categories.system_description',
                'icon' => 'fa-tools',
                'sort_order' => 5,
                'is_active' => true,
            ],
        ];

        foreach ($categories as $category) {
            DB::table('cmis.app_categories')->insert($category);
        }

        // Insert apps
        $apps = [
            // ========== CORE APPS (Always visible) ==========
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'dashboard',
                'name_key' => 'marketplace.apps.dashboard.name',
                'description_key' => 'marketplace.apps.dashboard.description',
                'icon' => 'fa-home',
                'category' => 'core',
                'route_name' => 'orgs.dashboard.index',
                'route_prefix' => 'dashboard',
                'is_core' => true,
                'is_premium' => false,
                'sort_order' => 0,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'social-media',
                'name_key' => 'marketplace.apps.social_media.name',
                'description_key' => 'marketplace.apps.social_media.description',
                'icon' => 'fa-share-alt',
                'category' => 'core',
                'route_name' => 'orgs.social.index',
                'route_prefix' => 'social',
                'is_core' => true,
                'is_premium' => false,
                'sort_order' => 1,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => json_encode([
                    'sub_routes' => ['orgs.social.history.index', 'orgs.social.calendar'],
                ]),
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'profile-groups',
                'name_key' => 'marketplace.apps.profile_groups.name',
                'description_key' => 'marketplace.apps.profile_groups.description',
                'icon' => 'fa-users-cog',
                'category' => 'core',
                'route_name' => 'orgs.settings.profile-groups.index',
                'route_prefix' => 'settings/profile-groups',
                'is_core' => true,
                'is_premium' => false,
                'sort_order' => 2,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'inbox',
                'name_key' => 'marketplace.apps.inbox.name',
                'description_key' => 'marketplace.apps.inbox.description',
                'icon' => 'fa-inbox',
                'category' => 'core',
                'route_name' => 'orgs.inbox.index',
                'route_prefix' => 'inbox',
                'is_core' => true,
                'is_premium' => false,
                'sort_order' => 3,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'settings',
                'name_key' => 'marketplace.apps.settings.name',
                'description_key' => 'marketplace.apps.settings.description',
                'icon' => 'fa-cog',
                'category' => 'core',
                'route_name' => 'orgs.settings.organization',
                'route_prefix' => 'settings',
                'is_core' => true,
                'is_premium' => false,
                'sort_order' => 4,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => json_encode([
                    'sub_routes' => [
                        'orgs.settings.user',
                        'orgs.settings.platform-connections.index',
                        'orgs.settings.profiles.index',
                        'orgs.team.index',
                    ],
                ]),
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'marketplace',
                'name_key' => 'marketplace.apps.marketplace.name',
                'description_key' => 'marketplace.apps.marketplace.description',
                'icon' => 'fa-store',
                'category' => 'core',
                'route_name' => 'orgs.marketplace.index',
                'route_prefix' => 'marketplace',
                'is_core' => true,
                'is_premium' => false,
                'sort_order' => 99,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],

            // ========== MARKETING APPS ==========
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'campaigns',
                'name_key' => 'marketplace.apps.campaigns.name',
                'description_key' => 'marketplace.apps.campaigns.description',
                'icon' => 'fa-bullhorn',
                'category' => 'marketing',
                'route_name' => 'orgs.campaigns.index',
                'route_prefix' => 'campaigns',
                'is_core' => false,
                'is_premium' => false,
                'sort_order' => 0,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => json_encode([
                    'sub_routes' => ['orgs.campaigns.ad-sets', 'orgs.campaigns.ads'],
                ]),
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'audiences',
                'name_key' => 'marketplace.apps.audiences.name',
                'description_key' => 'marketplace.apps.audiences.description',
                'icon' => 'fa-users',
                'category' => 'marketing',
                'route_name' => 'orgs.audiences.index',
                'route_prefix' => 'audiences',
                'is_core' => false,
                'is_premium' => false,
                'sort_order' => 1,
                'dependencies' => '["campaigns"]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'influencers',
                'name_key' => 'marketplace.apps.influencers.name',
                'description_key' => 'marketplace.apps.influencers.description',
                'icon' => 'fa-star',
                'category' => 'marketing',
                'route_name' => 'orgs.influencer.index',
                'route_prefix' => 'influencer',
                'is_core' => false,
                'is_premium' => true,
                'sort_order' => 2,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'orchestration',
                'name_key' => 'marketplace.apps.orchestration.name',
                'description_key' => 'marketplace.apps.orchestration.description',
                'icon' => 'fa-project-diagram',
                'category' => 'marketing',
                'route_name' => 'orgs.orchestration.index',
                'route_prefix' => 'orchestration',
                'is_core' => false,
                'is_premium' => true,
                'sort_order' => 3,
                'dependencies' => '["campaigns"]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],

            // ========== ANALYTICS APPS ==========
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'analytics',
                'name_key' => 'marketplace.apps.analytics.name',
                'description_key' => 'marketplace.apps.analytics.description',
                'icon' => 'fa-chart-line',
                'category' => 'analytics',
                'route_name' => 'orgs.analytics.index',
                'route_prefix' => 'analytics',
                'is_core' => false,
                'is_premium' => false,
                'sort_order' => 0,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'predictive',
                'name_key' => 'marketplace.apps.predictive.name',
                'description_key' => 'marketplace.apps.predictive.description',
                'icon' => 'fa-brain',
                'category' => 'analytics',
                'route_name' => 'orgs.predictive.index',
                'route_prefix' => 'predictive',
                'is_core' => false,
                'is_premium' => true,
                'sort_order' => 1,
                'dependencies' => '["analytics"]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'ab-testing',
                'name_key' => 'marketplace.apps.ab_testing.name',
                'description_key' => 'marketplace.apps.ab_testing.description',
                'icon' => 'fa-flask',
                'category' => 'analytics',
                'route_name' => 'orgs.ab-testing.index',
                'route_prefix' => 'ab-testing',
                'is_core' => false,
                'is_premium' => true,
                'sort_order' => 2,
                'dependencies' => '["analytics"]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'optimization',
                'name_key' => 'marketplace.apps.optimization.name',
                'description_key' => 'marketplace.apps.optimization.description',
                'icon' => 'fa-rocket',
                'category' => 'analytics',
                'route_name' => 'orgs.optimization.index',
                'route_prefix' => 'optimization',
                'is_core' => false,
                'is_premium' => true,
                'sort_order' => 3,
                'dependencies' => '["analytics", "campaigns"]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],

            // ========== AI APPS ==========
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'ai-assistant',
                'name_key' => 'marketplace.apps.ai_assistant.name',
                'description_key' => 'marketplace.apps.ai_assistant.description',
                'icon' => 'fa-robot',
                'category' => 'ai',
                'route_name' => 'orgs.ai.assistant.index',
                'route_prefix' => 'ai/assistant',
                'is_core' => false,
                'is_premium' => false,
                'sort_order' => 0,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'knowledge-base',
                'name_key' => 'marketplace.apps.knowledge_base.name',
                'description_key' => 'marketplace.apps.knowledge_base.description',
                'icon' => 'fa-book',
                'category' => 'ai',
                'route_name' => 'orgs.knowledge.index',
                'route_prefix' => 'knowledge',
                'is_core' => false,
                'is_premium' => false,
                'sort_order' => 1,
                'dependencies' => '["ai-assistant"]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'social-listening',
                'name_key' => 'marketplace.apps.social_listening.name',
                'description_key' => 'marketplace.apps.social_listening.description',
                'icon' => 'fa-ear-listen',
                'category' => 'ai',
                'route_name' => 'orgs.listening.index',
                'route_prefix' => 'listening',
                'is_core' => false,
                'is_premium' => true,
                'sort_order' => 2,
                'dependencies' => '["ai-assistant"]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],

            // ========== AUTOMATION APPS ==========
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'automation',
                'name_key' => 'marketplace.apps.automation.name',
                'description_key' => 'marketplace.apps.automation.description',
                'icon' => 'fa-cogs',
                'category' => 'automation',
                'route_name' => 'orgs.automation.index',
                'route_prefix' => 'automation',
                'is_core' => false,
                'is_premium' => true,
                'sort_order' => 0,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'workflows',
                'name_key' => 'marketplace.apps.workflows.name',
                'description_key' => 'marketplace.apps.workflows.description',
                'icon' => 'fa-sitemap',
                'category' => 'automation',
                'route_name' => 'orgs.workflows.index',
                'route_prefix' => 'workflows',
                'is_core' => false,
                'is_premium' => true,
                'sort_order' => 1,
                'dependencies' => '["automation"]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'alerts',
                'name_key' => 'marketplace.apps.alerts.name',
                'description_key' => 'marketplace.apps.alerts.description',
                'icon' => 'fa-bell',
                'category' => 'automation',
                'route_name' => 'orgs.alerts.index',
                'route_prefix' => 'alerts',
                'is_core' => false,
                'is_premium' => false,
                'sort_order' => 2,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],

            // ========== SYSTEM APPS ==========
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'exports',
                'name_key' => 'marketplace.apps.exports.name',
                'description_key' => 'marketplace.apps.exports.description',
                'icon' => 'fa-download',
                'category' => 'system',
                'route_name' => 'orgs.exports.index',
                'route_prefix' => 'exports',
                'is_core' => false,
                'is_premium' => false,
                'sort_order' => 0,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'dashboard-builder',
                'name_key' => 'marketplace.apps.dashboard_builder.name',
                'description_key' => 'marketplace.apps.dashboard_builder.description',
                'icon' => 'fa-th-large',
                'category' => 'system',
                'route_name' => 'orgs.dashboard-builder.index',
                'route_prefix' => 'dashboard-builder',
                'is_core' => false,
                'is_premium' => true,
                'sort_order' => 1,
                'dependencies' => '["analytics"]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'products',
                'name_key' => 'marketplace.apps.products.name',
                'description_key' => 'marketplace.apps.products.description',
                'icon' => 'fa-box',
                'category' => 'system',
                'route_name' => 'orgs.products.index',
                'route_prefix' => 'products',
                'is_core' => false,
                'is_premium' => false,
                'sort_order' => 2,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
            [
                'app_id' => Str::uuid()->toString(),
                'slug' => 'creative-assets',
                'name_key' => 'marketplace.apps.creative_assets.name',
                'description_key' => 'marketplace.apps.creative_assets.description',
                'icon' => 'fa-images',
                'category' => 'system',
                'route_name' => 'orgs.creative.assets.index',
                'route_prefix' => 'creative',
                'is_core' => false,
                'is_premium' => false,
                'sort_order' => 3,
                'dependencies' => '[]',
                'required_permissions' => '[]',
                'metadata' => '{}',
            ],
        ];

        $now = now();
        foreach ($apps as $app) {
            $app['created_at'] = $now;
            $app['updated_at'] = $now;
            DB::table('cmis.marketplace_apps')->insert($app);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::table('cmis.marketplace_apps')->truncate();
        DB::table('cmis.app_categories')->truncate();
    }
};
